# saitranslate scratch: batch B of 3 (locales hi, hr, hu, id, it, ja, ko, nl, no, pl)
TRANS = {
    'hi': {
        'TabThemes': 'थीम और ऐप्स',
        'TabBetterDiscord': 'BetterDiscord प्लगइन्स',
        'BdPlugins': 'BETTERDISCORD प्लगइन्स',
        'BdInstallSelected': 'लागू करें / इंस्टॉल करें',
        'BdUninstallSelected': 'अनइंस्टॉल करें',
        'BdOpenFolder': 'प्लगइन फ़ोल्डर',
        'BdRefresh': 'रिफ़्रेश करें',
        'BdAvailablePlugins': 'उपलब्ध प्लगइन्स',
        'BdPluginInfo': 'प्लगइन जानकारी',
        'BdLog': 'लॉग',
        'BdInstalled': 'इंस्टॉल किए गए',
        'BdAvailable': 'उपलब्ध',
        'BdStatusReady': 'BetterDiscord प्लगइन्स का पथ: {0} (तैयार)',
        'BdStatusNotFound': 'BetterDiscord प्लगइन्स फ़ोल्डर नहीं मिला: {0}',
        'BdStatusRefreshed': 'BetterDiscord प्लगइन्स की स्थिति रिफ़्रेश हुई।',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'रोने वाले, उदास और विषैले इमोजी को खुश और मज़ेदार इमोजी से बदलता है:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'MutationObserver के ज़रिए संदेशों, रिएक्शन्स और Twemoji एसेट्स की गतिशील निगरानी करता है।',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Discord में स्टिकर को पूरी तरह बंद और हटा देता है:',
            '  - चैट संदेशों में स्टिकर दिखना छिपाता है',
            '  - इनपुट बार से स्टिकर बटन छिपाता है',
            '  - ऑटोकम्प्लीट सुझावों से स्टिकर छिपाता है',
            '  - केवल स्टिकर वाली खाली संदेश पंक्तियों को अपने आप सिकोड़ देता है',
            '',
            'BdApi.DOM.addStyle से बिना देरी CSS इंजेक्ट करता है और सक्रिय DOM क्लीनर का उपयोग करता है।',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Discord में सभी GIF को पूरी तरह बंद और हटा देता है:',
            '  - चैट में GIF इमेज, वीडियो और ऑटोप्ले पूर्वावलोकन छिपाता है',
            '  - इनपुट बार से GIF बटन छिपाता है',
            '  - एक्सप्रेशन चुनने वाले में GIF टैब छिपाता है',
            '  - Tenor और Giphy एम्बेड छिपाता है',
            '  - केवल GIF वाली खाली संदेश पंक्तियों को अपने आप सिकोड़ देता है',
            '',
            'BdApi.DOM.addStyle से बिना देरी CSS इंजेक्ट करता है और सक्रिय DOM क्लीनर का उपयोग करता है।',
        ],
    },
    'hr': {
        'TabThemes': 'Teme i aplikacije',
        'TabBetterDiscord': 'BetterDiscord dodaci',
        'BdPlugins': 'BETTERDISCORD DODACI',
        'BdInstallSelected': 'PRIMIJENI / INSTALIRAJ',
        'BdUninstallSelected': 'DEINSTALIRAJ',
        'BdOpenFolder': 'MAPA DODATAKA',
        'BdRefresh': 'OSVJEŽI',
        'BdAvailablePlugins': 'DOSTUPNI DODACI',
        'BdPluginInfo': 'PODACI O DODATKU',
        'BdLog': 'ZAPISNIK',
        'BdInstalled': 'Instalirano',
        'BdAvailable': 'Dostupno',
        'BdStatusReady': 'Putanja do BetterDiscord dodataka: {0} (Spremno)',
        'BdStatusNotFound': 'Mapa BetterDiscord dodataka nije pronađena: {0}',
        'BdStatusRefreshed': 'Stanje BetterDiscord dodataka je osvježeno.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Zamjenjuje emojije koji plaču, tužne i toksične vedrima i smiješnima:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Dinamički prati poruke, reakcije i Twemoji sadržaje pomoću MutationObservera.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Potpuno isključuje i uklanja naljepnice u Discordu:',
            '  - Skriva prikaz naljepnica u porukama',
            '  - Skriva gumb naljepnica iz trake za unos',
            '  - Skriva naljepnice iz prijedloga za automatsko dovršavanje',
            '  - Automatski skuplja prazne retke koji sadrže samo naljepnice',
            '',
            'Koristi CSS ubrizgavanje bez odgode putem BdApi.DOM.addStyle i aktivnog čistača DOM-a.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Potpuno isključuje i uklanja sve GIF-ove u Discordu:',
            '  - Skriva GIF slike, videozapise i preglede s automatskom reprodukcijom u chatu',
            '  - Skriva gumb GIF iz trake za unos',
            '  - Skriva kartice GIF u izborniku izraza',
            '  - Skriva Tenor i Giphy ugrađene sadržaje',
            '  - Automatski skuplja prazne retke koji sadrže samo GIF-ove',
            '',
            'Koristi CSS ubrizgavanje bez odgode putem BdApi.DOM.addStyle i aktivnog čistača DOM-a.',
        ],
    },
    'hu': {
        'TabThemes': 'Témák és alkalmazások',
        'TabBetterDiscord': 'BetterDiscord bővítmények',
        'BdPlugins': 'BETTERDISCORD BŐVÍTMÉNYEK',
        'BdInstallSelected': 'ALKALMAZ / TELEPÍT',
        'BdUninstallSelected': 'ELTÁVOLÍT',
        'BdOpenFolder': 'BŐVÍTMÉNYMAPPA',
        'BdRefresh': 'FRISSÍTÉS',
        'BdAvailablePlugins': 'ELÉRHETŐ BŐVÍTMÉNYEK',
        'BdPluginInfo': 'BŐVÍTMÉNYADATOK',
        'BdLog': 'NAPLÓ',
        'BdInstalled': 'Telepített',
        'BdAvailable': 'Elérhető',
        'BdStatusReady': 'A BetterDiscord bővítmények útvonala: {0} (Kész)',
        'BdStatusNotFound': 'A BetterDiscord bővítménymappa nem található: {0}',
        'BdStatusRefreshed': 'A BetterDiscord bővítmények állapota frissítve.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'A síró, szomorú és mérgező emojikat vidámakra és viccesekre cseréli:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'A MutationObserverrel dinamikusan figyeli az üzeneteket, reakciókat és Twemoji-elemeket.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Teljesen kikapcsolja és eltávolítja a matricákat a Discordban:',
            '  - Elrejti a matricák megjelenítését a csevegőüzenetekben',
            '  - Elrejti a matrica gombot a beviteli sávból',
            '  - Elrejti a matricákat az automatikus kiegészítés javaslatai közül',
            '  - Automatikusan összecsukja a csak matricát tartalmazó üres sorokat',
            '',
            'Késleltetés nélküli CSS-injektálást használ a BdApi.DOM.addStyle-lal és aktív DOM-tisztítót.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Teljesen kikapcsolja és eltávolítja az összes GIF-et a Discordban:',
            '  - Elrejti a GIF-képeket, videókat és az automatikusan lejátszott előnézeteket a csevegésben',
            '  - Elrejti a GIF gombot a beviteli sávból',
            '  - Elrejti a GIF füleket a kifejezésválasztóban',
            '  - Elrejti a Tenor és Giphy beágyazásokat',
            '  - Automatikusan összecsukja a csak GIF-et tartalmazó üres sorokat',
            '',
            'Késleltetés nélküli CSS-injektálást használ a BdApi.DOM.addStyle-lal és aktív DOM-tisztítót.',
        ],
    },
    'id': {
        'TabThemes': 'Tema & aplikasi',
        'TabBetterDiscord': 'Plugin BetterDiscord',
        'BdPlugins': 'PLUGIN BETTERDISCORD',
        'BdInstallSelected': 'TERAPKAN / PASANG',
        'BdUninstallSelected': 'Copot pemasangan',
        'BdOpenFolder': 'FOLDER PLUGIN',
        'BdRefresh': 'SEGARKAN',
        'BdAvailablePlugins': 'PLUGIN TERSEDIA',
        'BdPluginInfo': 'INFO PLUGIN',
        'BdLog': 'LOG',
        'BdInstalled': 'Terpasang',
        'BdAvailable': 'Tersedia',
        'BdStatusReady': 'Jalur plugin BetterDiscord: {0} (Siap)',
        'BdStatusNotFound': 'Folder plugin BetterDiscord tidak ditemukan: {0}',
        'BdStatusRefreshed': 'Status plugin BetterDiscord disegarkan.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Mengganti emoji menangis, sedih, dan toksik dengan yang ceria dan lucu:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Memantau pesan, reaksi, dan aset Twemoji secara dinamis melalui MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Menonaktifkan dan menghapus stiker di Discord sepenuhnya:',
            '  - Menyembunyikan tampilan stiker pada pesan obrolan',
            '  - Menyembunyikan tombol stiker dari bilah input',
            '  - Menyembunyikan stiker dari saran pelengkapan otomatis',
            '  - Melipat otomatis baris pesan kosong yang hanya berisi stiker',
            '',
            'Memakai injeksi CSS tanpa jeda melalui BdApi.DOM.addStyle dan pembersih DOM aktif.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Menonaktifkan dan menghapus semua GIF di Discord sepenuhnya:',
            '  - Menyembunyikan gambar, video, dan pratinjau putar-otomatis GIF di obrolan',
            '  - Menyembunyikan tombol GIF dari bilah input',
            '  - Menyembunyikan tab GIF di pemilih ekspresi',
            '  - Menyembunyikan sematan Tenor dan Giphy',
            '  - Melipat otomatis baris pesan kosong yang hanya berisi GIF',
            '',
            'Memakai injeksi CSS tanpa jeda melalui BdApi.DOM.addStyle dan pembersih DOM aktif.',
        ],
    },
    'it': {
        'TabThemes': 'Temi e app',
        'TabBetterDiscord': 'Plugin di BetterDiscord',
        'BdPlugins': 'PLUGIN DI BETTERDISCORD',
        'BdInstallSelected': 'APPLICA / INSTALLA',
        'BdUninstallSelected': 'DISINSTALLA',
        'BdOpenFolder': 'CARTELLA DEI PLUGIN',
        'BdRefresh': 'AGGIORNA',
        'BdAvailablePlugins': 'PLUGIN DISPONIBILI',
        'BdPluginInfo': 'INFORMAZIONI SUL PLUGIN',
        'BdLog': 'REGISTRO',
        'BdInstalled': 'Installati',
        'BdAvailable': 'Disponibili',
        'BdStatusReady': 'Percorso dei plugin di BetterDiscord: {0} (Pronto)',
        'BdStatusNotFound': 'Cartella dei plugin di BetterDiscord non trovata: {0}',
        'BdStatusRefreshed': 'Stato dei plugin di BetterDiscord aggiornato.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Sostituisce le emoji piangenti, tristi e tossiche con altre allegre e divertenti:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Monitora dinamicamente messaggi, reazioni e risorse Twemoji tramite MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Disattiva e rimuove completamente gli sticker in Discord:',
            '  - Nasconde la visualizzazione degli sticker nei messaggi della chat',
            '  - Nasconde il pulsante degli sticker dalla barra di input',
            '  - Nasconde gli sticker dai suggerimenti di completamento automatico',
            '  - Comprime automaticamente le righe vuote che contengono solo sticker',
            '',
            'Usa l’iniezione CSS senza latenza tramite BdApi.DOM.addStyle e un ripulitore DOM attivo.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Disattiva e rimuove completamente tutti i GIF in Discord:',
            '  - Nasconde immagini e video GIF e le anteprime con riproduzione automatica in chat',
            '  - Nasconde il pulsante GIF dalla barra di input',
            '  - Nasconde le schede GIF nel selettore delle espressioni',
            '  - Nasconde gli incorporamenti di Tenor e Giphy',
            '  - Comprime automaticamente le righe vuote che contengono solo GIF',
            '',
            'Usa l’iniezione CSS senza latenza tramite BdApi.DOM.addStyle e un ripulitore DOM attivo.',
        ],
    },
    'ja': {
        'TabThemes': 'テーマとアプリ',
        'TabBetterDiscord': 'BetterDiscord プラグイン',
        'BdPlugins': 'BETTERDISCORD プラグイン',
        'BdInstallSelected': '適用 / インストール',
        'BdUninstallSelected': 'アンインストール',
        'BdOpenFolder': 'プラグインフォルダ',
        'BdRefresh': '更新',
        'BdAvailablePlugins': '利用可能なプラグイン',
        'BdPluginInfo': 'プラグイン情報',
        'BdLog': 'ログ',
        'BdInstalled': 'インストール済み',
        'BdAvailable': '利用可能',
        'BdStatusReady': 'BetterDiscord プラグインのパス: {0} (準備完了)',
        'BdStatusNotFound': 'BetterDiscord プラグインフォルダが見つかりません: {0}',
        'BdStatusRefreshed': 'BetterDiscord プラグインの状態を更新しました。',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            '泣き・悲しみ・有害な絵文字を、明るくて面白い絵文字に置き換えます:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'MutationObserver でメッセージ・リアクション・Twemoji アセットを動的に監視します。',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Discord のステッカーを完全に無効化して削除します:',
            '  - チャットのメッセージでステッカーの表示を隠します',
            '  - 入力バーからステッカーボタンを隠します',
            '  - 自動補完の候補からステッカーを隠します',
            '  - ステッカーだけの空のメッセージ行を自動で折りたたみます',
            '',
            'BdApi.DOM.addStyle による遅延のない CSS 注入と、常時動作する DOM クリーナーを使います。',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Discord のすべての GIF を完全に無効化して削除します:',
            '  - チャットの GIF 画像・動画・自動再生プレビューを隠します',
            '  - 入力バーから GIF ボタンを隠します',
            '  - 絵文字・ステッカー選択の GIF タブを隠します',
            '  - Tenor と Giphy の埋め込みを隠します',
            '  - GIF だけの空のメッセージ行を自動で折りたたみます',
            '',
            'BdApi.DOM.addStyle による遅延のない CSS 注入と、常時動作する DOM クリーナーを使います。',
        ],
    },
    'ko': {
        'TabThemes': '테마 및 앱',
        'TabBetterDiscord': 'BetterDiscord 플러그인',
        'BdPlugins': 'BETTERDISCORD 플러그인',
        'BdInstallSelected': '적용 / 설치',
        'BdUninstallSelected': '제거',
        'BdOpenFolder': '플러그인 폴더',
        'BdRefresh': '새로 고침',
        'BdAvailablePlugins': '사용 가능한 플러그인',
        'BdPluginInfo': '플러그인 정보',
        'BdLog': '로그',
        'BdInstalled': '설치됨',
        'BdAvailable': '사용 가능',
        'BdStatusReady': 'BetterDiscord 플러그인 경로: {0} (준비됨)',
        'BdStatusNotFound': 'BetterDiscord 플러그인 폴더를 찾을 수 없습니다: {0}',
        'BdStatusRefreshed': 'BetterDiscord 플러그인 상태를 새로 고쳤습니다.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            '우는, 슬픈, 유해한 이모지를 밝고 재미있는 이모지로 바꿉니다:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'MutationObserver 로 메시지, 반응, Twemoji 자산을 실시간으로 감시합니다.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Discord 의 스티커를 완전히 끄고 제거합니다:',
            '  - 채팅 메시지의 스티커 표시를 숨깁니다',
            '  - 입력창에서 스티커 버튼을 숨깁니다',
            '  - 자동 완성 제안에서 스티커를 숨깁니다',
            '  - 스티커만 있는 빈 메시지 줄을 자동으로 접습니다',
            '',
            'BdApi.DOM.addStyle 로 지연 없는 CSS 주입을 하고 상시 동작하는 DOM 정리기를 사용합니다.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Discord 의 모든 GIF 를 완전히 끄고 제거합니다:',
            '  - 채팅의 GIF 이미지, 동영상, 자동 재생 미리보기를 숨깁니다',
            '  - 입력창에서 GIF 버튼을 숨깁니다',
            '  - 이모지 선택기의 GIF 탭을 숨깁니다',
            '  - Tenor 와 Giphy 임베드를 숨깁니다',
            '  - GIF 만 있는 빈 메시지 줄을 자동으로 접습니다',
            '',
            'BdApi.DOM.addStyle 로 지연 없는 CSS 주입을 하고 상시 동작하는 DOM 정리기를 사용합니다.',
        ],
    },
    'nl': {
        'TabThemes': 'Thema’s en apps',
        'TabBetterDiscord': 'BetterDiscord-plug-ins',
        'BdPlugins': 'BETTERDISCORD-PLUG-INS',
        'BdInstallSelected': 'TOEPASSEN / INSTALLEREN',
        'BdUninstallSelected': 'VERWIJDEREN',
        'BdOpenFolder': 'PLUG-INMAP',
        'BdRefresh': 'VERVERSEN',
        'BdAvailablePlugins': 'BESCHIKBARE PLUG-INS',
        'BdPluginInfo': 'PLUG-ININFO',
        'BdLog': 'LOGBOEK',
        'BdInstalled': 'Geïnstalleerd',
        'BdAvailable': 'Beschikbaar',
        'BdStatusReady': 'Pad naar BetterDiscord-plug-ins: {0} (Gereed)',
        'BdStatusNotFound': 'Map met BetterDiscord-plug-ins niet gevonden: {0}',
        'BdStatusRefreshed': 'Status van BetterDiscord-plug-ins vernieuwd.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Vervangt huilende, verdrietige en giftige emoji’s door vrolijke en grappige:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Volgt berichten, reacties en Twemoji-assets dynamisch via een MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Schakelt stickers in Discord volledig uit en verwijdert ze:',
            '  - Verbergt de weergave van stickers in chatberichten',
            '  - Verbergt de stickersknop in de invoerbalk',
            '  - Verbergt stickers in de suggesties van automatisch aanvullen',
            '  - Vouwt lege berichtregels met alleen stickers automatisch in',
            '',
            'Gebruikt CSS-injectie zonder vertraging via BdApi.DOM.addStyle en een actieve DOM-opruimer.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Schakelt alle GIF’s in Discord volledig uit en verwijdert ze:',
            '  - Verbergt GIF-afbeeldingen, video’s en voorbeelden met automatisch afspelen in de chat',
            '  - Verbergt de GIF-knop in de invoerbalk',
            '  - Verbergt GIF-tabbladen in de expressiekiezer',
            '  - Verbergt Tenor- en Giphy-insluitingen',
            '  - Vouwt lege berichtregels met alleen GIF’s automatisch in',
            '',
            'Gebruikt CSS-injectie zonder vertraging via BdApi.DOM.addStyle en een actieve DOM-opruimer.',
        ],
    },
    'no': {
        'TabThemes': 'Temaer og apper',
        'TabBetterDiscord': 'BetterDiscord-utvidelser',
        'BdPlugins': 'BETTERDISCORD-UTVIDELSER',
        'BdInstallSelected': 'BRUK / INSTALLER',
        'BdUninstallSelected': 'AVINSTALLER',
        'BdOpenFolder': 'UTVIDELSESMAPPE',
        'BdRefresh': 'OPPDATER',
        'BdAvailablePlugins': 'TILGJENGELIGE UTVIDELSER',
        'BdPluginInfo': 'UTVIDELSESINFO',
        'BdLog': 'LOGG',
        'BdInstalled': 'Installert',
        'BdAvailable': 'Tilgjengelig',
        'BdStatusReady': 'Sti til BetterDiscord-utvidelser: {0} (Klar)',
        'BdStatusNotFound': 'Mappen for BetterDiscord-utvidelser ble ikke funnet: {0}',
        'BdStatusRefreshed': 'Statusen for BetterDiscord-utvidelser er oppdatert.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Erstatter gråtende, triste og giftige emoji-er med glade og morsomme:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Overvåker meldinger, reaksjoner og Twemoji-ressurser dynamisk via MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Slår av og fjerner klistremerker i Discord fullstendig:',
            '  - Skjuler visning av klistremerker i chatmeldinger',
            '  - Skjuler klistremerkeknappen i inndatafeltet',
            '  - Skjuler klistremerker i forslagene fra autofullføring',
            '  - Slår automatisk sammen tomme meldingslinjer med bare klistremerker',
            '',
            'Bruker CSS-injeksjon uten forsinkelse via BdApi.DOM.addStyle og en aktiv DOM-rydder.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Slår av og fjerner alle GIF-er i Discord fullstendig:',
            '  - Skjuler GIF-bilder, videoer og forhåndsvisninger med autospill i chatten',
            '  - Skjuler GIF-knappen i inndatafeltet',
            '  - Skjuler GIF-faner i uttrykksvelgeren',
            '  - Skjuler Tenor- og Giphy-innbygging',
            '  - Slår automatisk sammen tomme meldingslinjer med bare GIF-er',
            '',
            'Bruker CSS-injeksjon uten forsinkelse via BdApi.DOM.addStyle og en aktiv DOM-rydder.',
        ],
    },
    'pl': {
        'TabThemes': 'Motywy i aplikacje',
        'TabBetterDiscord': 'Wtyczki BetterDiscord',
        'BdPlugins': 'WTYCZKI BETTERDISCORD',
        'BdInstallSelected': 'ZASTOSUJ / ZAINSTALUJ',
        'BdUninstallSelected': 'ODINSTALUJ',
        'BdOpenFolder': 'FOLDER WTYCZEK',
        'BdRefresh': 'ODŚWIEŻ',
        'BdAvailablePlugins': 'DOSTĘPNE WTYCZKI',
        'BdPluginInfo': 'INFORMACJE O WTYCZCE',
        'BdLog': 'DZIENNIK',
        'BdInstalled': 'Zainstalowane',
        'BdAvailable': 'Dostępne',
        'BdStatusReady': 'Ścieżka wtyczek BetterDiscord: {0} (Gotowe)',
        'BdStatusNotFound': 'Nie znaleziono folderu wtyczek BetterDiscord: {0}',
        'BdStatusRefreshed': 'Stan wtyczek BetterDiscord odświeżony.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Zastępuje płaczące, smutne i toksyczne emoji wesołymi i zabawnymi:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Dynamicznie obserwuje wiadomości, reakcje i zasoby Twemoji przez MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Całkowicie wyłącza i usuwa naklejki w Discordzie:',
            '  - Ukrywa wyświetlanie naklejek w wiadomościach czatu',
            '  - Ukrywa przycisk naklejek na pasku wprowadzania',
            '  - Ukrywa naklejki w podpowiedziach autouzupełniania',
            '  - Automatycznie zwija puste wiersze zawierające tylko naklejki',
            '',
            'Wykorzystuje wstrzykiwanie CSS bez opóźnień przez BdApi.DOM.addStyle i aktywny czyściciel DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Całkowicie wyłącza i usuwa wszystkie GIF-y w Discordzie:',
            '  - Ukrywa obrazy i filmy GIF oraz podglądy z automatycznym odtwarzaniem na czacie',
            '  - Ukrywa przycisk GIF na pasku wprowadzania',
            '  - Ukrywa karty GIF w wyborze wyrażeń',
            '  - Ukrywa osadzenia Tenor i Giphy',
            '  - Automatycznie zwija puste wiersze zawierające tylko GIF-y',
            '',
            'Wykorzystuje wstrzykiwanie CSS bez opóźnień przez BdApi.DOM.addStyle i aktywny czyściciel DOM.',
        ],
    },
}
