# saitranslate scratch: batch C of 3 (locales pt, ro, sk, sv, th, tr, uk, vi, zh)
TRANS = {
    'pt': {
        'TabThemes': 'Temas e aplicativos',
        'TabBetterDiscord': 'Plugins do BetterDiscord',
        'BdPlugins': 'PLUGINS DO BETTERDISCORD',
        'BdInstallSelected': 'APLICAR / INSTALAR',
        'BdUninstallSelected': 'DESINSTALAR',
        'BdOpenFolder': 'PASTA DE PLUGINS',
        'BdRefresh': 'ATUALIZAR',
        'BdAvailablePlugins': 'PLUGINS DISPONÍVEIS',
        'BdPluginInfo': 'INFORMAÇÕES DO PLUGIN',
        'BdLog': 'REGISTRO',
        'BdInstalled': 'Instalados',
        'BdAvailable': 'Disponíveis',
        'BdStatusReady': 'Caminho dos plugins do BetterDiscord: {0} (Pronto)',
        'BdStatusNotFound': 'Pasta de plugins do BetterDiscord não encontrada: {0}',
        'BdStatusRefreshed': 'Status dos plugins do BetterDiscord atualizado.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Substitui emojis chorando, tristes e tóxicos por alegres e engraçados:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Monitora dinamicamente mensagens, reações e recursos do Twemoji via MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Desativa e remove completamente as figurinhas no Discord:',
            '  - Oculta a exibição de figurinhas nas mensagens do chat',
            '  - Oculta o botão de figurinhas da barra de entrada',
            '  - Oculta figurinhas das sugestões de preenchimento automático',
            '  - Recolhe automaticamente linhas vazias que só têm figurinhas',
            '',
            'Usa injeção de CSS sem latência via BdApi.DOM.addStyle e um limpador de DOM ativo.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Desativa e remove completamente todos os GIFs no Discord:',
            '  - Oculta imagens e vídeos GIF e as prévias com reprodução automática no chat',
            '  - Oculta o botão de GIF da barra de entrada',
            '  - Oculta as abas de GIF no seletor de expressões',
            '  - Oculta as incorporações do Tenor e do Giphy',
            '  - Recolhe automaticamente linhas vazias que só têm GIFs',
            '',
            'Usa injeção de CSS sem latência via BdApi.DOM.addStyle e um limpador de DOM ativo.',
        ],
    },
    'ro': {
        'TabThemes': 'Teme și aplicații',
        'TabBetterDiscord': 'Module BetterDiscord',
        'BdPlugins': 'MODULE BETTERDISCORD',
        'BdInstallSelected': 'APLICĂ / INSTALEAZĂ',
        'BdUninstallSelected': 'DEZINSTALEAZĂ',
        'BdOpenFolder': 'DOSARUL MODULELOR',
        'BdRefresh': 'REÎMPROSPĂTEAZĂ',
        'BdAvailablePlugins': 'MODULE DISPONIBILE',
        'BdPluginInfo': 'INFORMAȚII MODUL',
        'BdLog': 'JURNAL',
        'BdInstalled': 'Instalate',
        'BdAvailable': 'Disponibile',
        'BdStatusReady': 'Calea modulelor BetterDiscord: {0} (Pregătit)',
        'BdStatusNotFound': 'Dosarul modulelor BetterDiscord nu a fost găsit: {0}',
        'BdStatusRefreshed': 'Starea modulelor BetterDiscord a fost reîmprospătată.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Înlocuiește emoji plângăcioase, triste și toxice cu unele vesele și amuzante:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Monitorizează dinamic mesajele, reacțiile și resursele Twemoji prin MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Dezactivează și elimină complet stickerele din Discord:',
            '  - Ascunde afișarea stickerelor în mesajele din chat',
            '  - Ascunde butonul de stickere din bara de introducere',
            '  - Ascunde stickerele din sugestiile de completare automată',
            '  - Pliază automat rândurile goale care conțin doar stickere',
            '',
            'Folosește injectarea CSS fără întârziere prin BdApi.DOM.addStyle și un curățător DOM activ.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Dezactivează și elimină complet toate GIF-urile din Discord:',
            '  - Ascunde imaginile și videoclipurile GIF și previzualizările cu redare automată din chat',
            '  - Ascunde butonul GIF din bara de introducere',
            '  - Ascunde filele GIF din selectorul de expresii',
            '  - Ascunde încorporările Tenor și Giphy',
            '  - Pliază automat rândurile goale care conțin doar GIF-uri',
            '',
            'Folosește injectarea CSS fără întârziere prin BdApi.DOM.addStyle și un curățător DOM activ.',
        ],
    },
    'sk': {
        'TabThemes': 'Motívy a aplikácie',
        'TabBetterDiscord': 'Pluginy BetterDiscord',
        'BdPlugins': 'PLUGINY BETTERDISCORD',
        'BdInstallSelected': 'POUŽIŤ / NAINSTALOVAŤ',
        'BdUninstallSelected': 'ODINŠTALOVAŤ',
        'BdOpenFolder': 'PRIEČINOK PLUGINOV',
        'BdRefresh': 'OBNOVIŤ',
        'BdAvailablePlugins': 'DOSTUPNÉ PLUGINY',
        'BdPluginInfo': 'INFORMÁCIE O PLUGINE',
        'BdLog': 'ZÁZNAM',
        'BdInstalled': 'Nainštalované',
        'BdAvailable': 'Dostupné',
        'BdStatusReady': 'Cesta k pluginom BetterDiscord: {0} (Pripravené)',
        'BdStatusNotFound': 'Priečinok pluginov BetterDiscord sa nenašiel: {0}',
        'BdStatusRefreshed': 'Stav pluginov BetterDiscord bol obnovený.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Nahrádza plačúce, smutné a toxické emoji veselými a vtipnými:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Dynamicky sleduje správy, reakcie a podklady Twemoji pomocou MutationObservera.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Úplne vypína a odstraňuje samolepky v Discorde:',
            '  - Skrýva vykresľovanie samolepiek v správach',
            '  - Skrýva tlačidlo samolepiek na vstupnom paneli',
            '  - Skrýva samolepky z návrhov automatického dopĺňania',
            '  - Automaticky zbalí prázdne riadky obsahujúce len samolepky',
            '',
            'Používa vstrekovanie CSS bez latencie cez BdApi.DOM.addStyle a aktívny čistič DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Úplne vypína a odstraňuje všetky GIF-y v Discorde:',
            '  - Skrýva obrázky a videá GIF aj náhľady s automatickým prehrávaním v chate',
            '  - Skrýva tlačidlo GIF na vstupnom paneli',
            '  - Skrýva karty GIF vo výbere výrazov',
            '  - Skrýva vložené obsahy Tenor a Giphy',
            '  - Automaticky zbalí prázdne riadky obsahujúce len GIF-y',
            '',
            'Používa vstrekovanie CSS bez latencie cez BdApi.DOM.addStyle a aktívny čistič DOM.',
        ],
    },
    'sv': {
        'TabThemes': 'Teman och appar',
        'TabBetterDiscord': 'BetterDiscord-tillägg',
        'BdPlugins': 'BETTERDISCORD-TILLÄGG',
        'BdInstallSelected': 'TILLÄMPA / INSTALLERA',
        'BdUninstallSelected': 'AVINSTALLERA',
        'BdOpenFolder': 'TILLÄGGSMAPP',
        'BdRefresh': 'UPPDATERA',
        'BdAvailablePlugins': 'TILLGÄNGLIGA TILLÄGG',
        'BdPluginInfo': 'TILLÄGGSINFO',
        'BdLog': 'LOGG',
        'BdInstalled': 'Installerade',
        'BdAvailable': 'Tillgängliga',
        'BdStatusReady': 'Sökväg till BetterDiscord-tillägg: {0} (Klar)',
        'BdStatusNotFound': 'Mappen för BetterDiscord-tillägg hittades inte: {0}',
        'BdStatusRefreshed': 'Statusen för BetterDiscord-tillägg uppdaterades.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Ersätter gråtande, ledsna och giftiga emojis med glada och roliga:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Bevakar meddelanden, reaktioner och Twemoji-resurser dynamiskt via MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Stänger av och tar bort klistermärken i Discord helt:',
            '  - Döljer visning av klistermärken i chattmeddelanden',
            '  - Döljer klistermärkesknappen i inmatningsfältet',
            '  - Döljer klistermärken i förslagen från autokomplettering',
            '  - Fäller automatiskt ihop tomma meddelanderader med bara klistermärken',
            '',
            'Använder CSS-injektion utan fördröjning via BdApi.DOM.addStyle och en aktiv DOM-städare.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Stänger av och tar bort alla GIF-filer i Discord helt:',
            '  - Döljer GIF-bilder, videor och förhandsvisningar med autouppspelning i chatten',
            '  - Döljer GIF-knappen i inmatningsfältet',
            '  - Döljer GIF-flikar i uttrycksväljaren',
            '  - Döljer Tenor- och Giphy-inbäddningar',
            '  - Fäller automatiskt ihop tomma meddelanderader med bara GIF-filer',
            '',
            'Använder CSS-injektion utan fördröjning via BdApi.DOM.addStyle och en aktiv DOM-städare.',
        ],
    },
    'th': {
        'TabThemes': 'ธีมและแอป',
        'TabBetterDiscord': 'ปลั๊กอิน BetterDiscord',
        'BdPlugins': 'ปลั๊กอิน BETTERDISCORD',
        'BdInstallSelected': 'ใช้งาน / ติดตั้ง',
        'BdUninstallSelected': 'ถอนการติดตั้ง',
        'BdOpenFolder': 'โฟลเดอร์ปลั๊กอิน',
        'BdRefresh': 'รีเฟรช',
        'BdAvailablePlugins': 'ปลั๊กอินที่ใช้ได้',
        'BdPluginInfo': 'ข้อมูลปลั๊กอิน',
        'BdLog': 'บันทึก',
        'BdInstalled': 'ติดตั้งแล้ว',
        'BdAvailable': 'ใช้ได้',
        'BdStatusReady': 'พาธปลั๊กอิน BetterDiscord: {0} (พร้อม)',
        'BdStatusNotFound': 'ไม่พบโฟลเดอร์ปลั๊กอิน BetterDiscord: {0}',
        'BdStatusRefreshed': 'รีเฟรชสถานะปลั๊กอิน BetterDiscord แล้ว',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'แทนที่อีโมจิร้องไห้ เศร้า และเป็นพิษ ด้วยอีโมจิที่สดใสและตลก:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'ติดตามข้อความ รีแอ็กชัน และไฟล์ Twemoji แบบไดนามิกผ่าน MutationObserver',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'ปิดและลบสติกเกอร์ใน Discord ทั้งหมด:',
            '  - ซ่อนการแสดงสติกเกอร์ในข้อความแชต',
            '  - ซ่อนปุ่มสติกเกอร์จากแถบพิมพ์',
            '  - ซ่อนสติกเกอร์จากคำแนะนำการเติมข้อความอัตโนมัติ',
            '  - ย่อบรรทัดข้อความว่างที่มีแค่สติกเกอร์โดยอัตโนมัติ',
            '',
            'ใช้การฉีด CSS แบบไร้ดีเลย์ผ่าน BdApi.DOM.addStyle และตัวล้าง DOM ที่ทำงานอยู่เสมอ',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'ปิดและลบ GIF ทั้งหมดใน Discord:',
            '  - ซ่อนภาพและวิดีโอ GIF รวมถึงตัวอย่างที่เล่นอัตโนมัติในแชต',
            '  - ซ่อนปุ่ม GIF จากแถบพิมพ์',
            '  - ซ่อนแท็บ GIF ในตัวเลือกอีโมจิ',
            '  - ซ่อนการฝังจาก Tenor และ Giphy',
            '  - ย่อบรรทัดข้อความว่างที่มีแค่ GIF โดยอัตโนมัติ',
            '',
            'ใช้การฉีด CSS แบบไร้ดีเลย์ผ่าน BdApi.DOM.addStyle และตัวล้าง DOM ที่ทำงานอยู่เสมอ',
        ],
    },
    'tr': {
        'TabThemes': 'Temalar ve uygulamalar',
        'TabBetterDiscord': 'BetterDiscord eklentileri',
        'BdPlugins': 'BETTERDISCORD EKLENTİLERİ',
        'BdInstallSelected': 'UYGULA / KUR',
        'BdUninstallSelected': 'KALDIR',
        'BdOpenFolder': 'EKLENTİ KLASÖRÜ',
        'BdRefresh': 'YENİLE',
        'BdAvailablePlugins': 'KULLANILABİLİR EKLENTİLER',
        'BdPluginInfo': 'EKLENTİ BİLGİSİ',
        'BdLog': 'GÜNLÜK',
        'BdInstalled': 'Kurulu',
        'BdAvailable': 'Kullanılabilir',
        'BdStatusReady': 'BetterDiscord eklentileri yolu: {0} (Hazır)',
        'BdStatusNotFound': 'BetterDiscord eklenti klasörü bulunamadı: {0}',
        'BdStatusRefreshed': 'BetterDiscord eklenti durumu yenilendi.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Ağlayan, üzgün ve zehirli emojileri neşeli ve komik olanlarla değiştirir:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Mesajları, tepkileri ve Twemoji varlıklarını MutationObserver ile dinamik izler.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Discord’daki çıkartmaları tamamen kapatır ve kaldırır:',
            '  - Sohbet mesajlarında çıkartma gösterimini gizler',
            '  - Giriş çubuğundaki çıkartma düğmesini gizler',
            '  - Otomatik tamamlama önerilerinden çıkartmaları gizler',
            '  - Yalnızca çıkartma içeren boş mesaj satırlarını otomatik daraltır',
            '',
            'BdApi.DOM.addStyle ile gecikmesiz CSS enjeksiyonu ve etkin bir DOM temizleyici kullanır.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Discord’daki tüm GIF’leri tamamen kapatır ve kaldırır:',
            '  - Sohbetteki GIF görsellerini, videolarını ve otomatik oynatma önizlemelerini gizler',
            '  - Giriş çubuğundaki GIF düğmesini gizler',
            '  - İfade seçicideki GIF sekmelerini gizler',
            '  - Tenor ve Giphy yerleştirmelerini gizler',
            '  - Yalnızca GIF içeren boş mesaj satırlarını otomatik daraltır',
            '',
            'BdApi.DOM.addStyle ile gecikmesiz CSS enjeksiyonu ve etkin bir DOM temizleyici kullanır.',
        ],
    },
    'uk': {
        'TabThemes': 'Теми та застосунки',
        'TabBetterDiscord': 'Плагіни BetterDiscord',
        'BdPlugins': 'ПЛАГІНИ BETTERDISCORD',
        'BdInstallSelected': 'ЗАСТОСУВАТИ / ВСТАНОВИТИ',
        'BdUninstallSelected': 'ВИДАЛИТИ',
        'BdOpenFolder': 'ТЕКА ПЛАГІНІВ',
        'BdRefresh': 'ОНОВИТИ',
        'BdAvailablePlugins': 'ДОСТУПНІ ПЛАГІНИ',
        'BdPluginInfo': 'ІНФОРМАЦІЯ ПРО ПЛАГІН',
        'BdLog': 'ЖУРНАЛ',
        'BdInstalled': 'Встановлені',
        'BdAvailable': 'Доступні',
        'BdStatusReady': 'Шлях до плагінів BetterDiscord: {0} (Готово)',
        'BdStatusNotFound': 'Теку плагінів BetterDiscord не знайдено: {0}',
        'BdStatusRefreshed': 'Стан плагінів BetterDiscord оновлено.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Замінює плаксиві, сумні та токсичні емодзі на веселі й кумедні:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Динамічно відстежує повідомлення, реакції та ресурси Twemoji через MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Повністю вимикає та прибирає стікери в Discord:',
            '  - Приховує показ стікерів у повідомленнях чату',
            '  - Приховує кнопку стікерів із панелі введення',
            '  - Приховує стікери з підказок автодоповнення',
            '  - Автоматично згортає порожні рядки, що містять лише стікери',
            '',
            'Використовує CSS-ін’єкцію без затримки через BdApi.DOM.addStyle та активний очищувач DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Повністю вимикає та прибирає всі GIF у Discord:',
            '  - Приховує GIF-зображення, відео та попередній перегляд з автовідтворенням у чаті',
            '  - Приховує кнопку GIF із панелі введення',
            '  - Приховує вкладки GIF у виборі емодзі',
            '  - Приховує вбудови Tenor і Giphy',
            '  - Автоматично згортає порожні рядки, що містять лише GIF',
            '',
            'Використовує CSS-ін’єкцію без затримки через BdApi.DOM.addStyle та активний очищувач DOM.',
        ],
    },
    'vi': {
        'TabThemes': 'Giao diện và ứng dụng',
        'TabBetterDiscord': 'Plugin BetterDiscord',
        'BdPlugins': 'PLUGIN BETTERDISCORD',
        'BdInstallSelected': 'ÁP DỤNG / CÀI ĐẶT',
        'BdUninstallSelected': 'GỠ CÀI ĐẶT',
        'BdOpenFolder': 'THƯ MỤC PLUGIN',
        'BdRefresh': 'LÀM MỚI',
        'BdAvailablePlugins': 'PLUGIN KHẢ DỤNG',
        'BdPluginInfo': 'THÔNG TIN PLUGIN',
        'BdLog': 'NHẬT KÝ',
        'BdInstalled': 'Đã cài',
        'BdAvailable': 'Khả dụng',
        'BdStatusReady': 'Đường dẫn plugin BetterDiscord: {0} (Sẵn sàng)',
        'BdStatusNotFound': 'Không tìm thấy thư mục plugin BetterDiscord: {0}',
        'BdStatusRefreshed': 'Đã làm mới trạng thái plugin BetterDiscord.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Thay emoji khóc, buồn và độc hại bằng emoji vui vẻ, hài hước:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Theo dõi động tin nhắn, cảm xúc và tài nguyên Twemoji qua MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Tắt và gỡ hoàn toàn nhãn dán trong Discord:',
            '  - Ẩn phần hiển thị nhãn dán trong tin nhắn trò chuyện',
            '  - Ẩn nút nhãn dán khỏi thanh nhập',
            '  - Ẩn nhãn dán khỏi gợi ý tự động hoàn thành',
            '  - Tự động thu gọn các dòng tin nhắn trống chỉ có nhãn dán',
            '',
            'Dùng chèn CSS không độ trễ qua BdApi.DOM.addStyle và bộ dọn DOM hoạt động thường trực.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Tắt và gỡ hoàn toàn mọi GIF trong Discord:',
            '  - Ẩn ảnh, video GIF và bản xem trước tự phát trong trò chuyện',
            '  - Ẩn nút GIF khỏi thanh nhập',
            '  - Ẩn thẻ GIF trong trình chọn biểu cảm',
            '  - Ẩn nội dung nhúng từ Tenor và Giphy',
            '  - Tự động thu gọn các dòng tin nhắn trống chỉ có GIF',
            '',
            'Dùng chèn CSS không độ trễ qua BdApi.DOM.addStyle và bộ dọn DOM hoạt động thường trực.',
        ],
    },
    'zh': {
        'TabThemes': '主题与应用',
        'TabBetterDiscord': 'BetterDiscord 插件',
        'BdPlugins': 'BETTERDISCORD 插件',
        'BdInstallSelected': '应用 / 安装',
        'BdUninstallSelected': '卸载',
        'BdOpenFolder': '插件文件夹',
        'BdRefresh': '刷新',
        'BdAvailablePlugins': '可用插件',
        'BdPluginInfo': '插件信息',
        'BdLog': '日志',
        'BdInstalled': '已安装',
        'BdAvailable': '可用',
        'BdStatusReady': 'BetterDiscord 插件路径：{0}（就绪）',
        'BdStatusNotFound': '未找到 BetterDiscord 插件文件夹：{0}',
        'BdStatusRefreshed': '已刷新 BetterDiscord 插件状态。',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            '把哭泣、悲伤和有毒的表情替换成开心有趣的表情：',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            '通过 MutationObserver 动态监视消息、回应与 Twemoji 素材。',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            '彻底关闭并移除 Discord 中的贴纸：',
            '  - 隐藏聊天消息中的贴纸显示',
            '  - 隐藏输入栏中的贴纸按钮',
            '  - 隐藏自动补全建议中的贴纸',
            '  - 自动折叠只有贴纸的空消息行',
            '',
            '通过 BdApi.DOM.addStyle 进行无延迟的 CSS 注入，并常驻清理 DOM。',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            '彻底关闭并移除 Discord 中的所有 GIF：',
            '  - 隐藏聊天中的 GIF 图片、视频与自动播放预览',
            '  - 隐藏输入栏中的 GIF 按钮',
            '  - 隐藏表情选择器中的 GIF 标签页',
            '  - 隐藏 Tenor 与 Giphy 嵌入内容',
            '  - 自动折叠只有 GIF 的空消息行',
            '',
            '通过 BdApi.DOM.addStyle 进行无延迟的 CSS 注入，并常驻清理 DOM。',
        ],
    },
}
