# saitranslate scratch: batch D -- the 9 GoodEmoji bullet lines per locale.
# Core's accepted reference (desktop/locales/ru.json) localizes the emoji NAMES
# (e.g. 'слезы -> смех'), not the raw identifiers. These replace the raw
# 'sob -> joy' bullets in batches A/B/C, keeping the exact 9-line count.

BULLETS = {
    'ar': ['الدموع -> الضحك', 'البكاء -> ابتسامة', 'التوسل -> رائع بالنظارات الشمسية',
           'الجمجمة -> ابتسامة خفيفة', 'زهرة ذابلة -> وردة متفتحة', 'مهرج -> إبهام للأعلى',
           'الحزن/العبوس -> الفرح/الابتسام', 'قلب مكسور -> قلب سليم',
           'الإصبع الأوسط -> علامة السلام'],
    'bg': ['сълзи -> смях', 'плач -> усмивка', 'умоляващ -> готин със слънчеви очила',
           'череп -> лека усмивка', 'увехтяло цвете -> разцъфнала роза', 'клоун -> палец нагоре',
           'тъга/намръщено -> радост/усмивка', 'разбито сърце -> здраво сърце',
           'среден пръст -> знак за мир'],
    'cs': ['slzy -> smích', 'pláč -> úsměv', 'prosebný -> frajer v brýlích',
           'lebka -> lehký úsměv', 'zvadlá květina -> rozkvetlá růže', 'klaun -> palec nahoru',
           'smutek/mračení -> radost/úsměv', 'zlomené srdce -> celé srdce',
           'prostředníček -> znamení míru'],
    'da': ['tårer -> latter', 'gråd -> smil', 'bønfaldende -> sej med solbriller',
           'kranie -> let smil', 'vissen blomst -> blomstrende rose', 'klovn -> tommel op',
           'trist/rynket -> glæde/smil', 'knust hjerte -> helt hjerte',
           'langfinger -> fredstegn'],
    'de': ['Tränen -> Lachen', 'Weinen -> Lächeln', 'bittend -> cool mit Sonnenbrille',
           'Totenkopf -> leichtes Lächeln', 'welke Blume -> blühende Rose', 'Clown -> Daumen hoch',
           'traurig/Stirnrunzeln -> Freude/Lächeln', 'gebrochenes Herz -> heiles Herz',
           'Mittelfinger -> Friedenszeichen'],
    'el': ['δάκρυα -> γέλιο', 'κλάμα -> χαμόγελο', 'ικετευτικό -> κουλ με γυαλιά',
           'κρανίο -> ελαφρύ χαμόγελο', 'μαραμένο λουλούδι -> ανθισμένο τριαντάφυλλο',
           'κλόουν -> αντίχειρας ψηλά', 'θλίψη/κατσούφιασμα -> χαρά/χαμόγελο',
           'ραγισμένη καρδιά -> γερή καρδιά', 'μεσαίο δάχτυλο -> σήμα ειρήνης'],
    'es': ['lágrimas -> risa', 'llanto -> sonrisa', 'suplicante -> guay con gafas de sol',
           'calavera -> leve sonrisa', 'flor marchita -> rosa florecida', 'payaso -> pulgar arriba',
           'tristeza/ceño -> alegría/sonrisa', 'corazón roto -> corazón entero',
           'dedo medio -> signo de paz'],
    'fi': ['kyyneleet -> nauru', 'itku -> hymy', 'anova -> siisti aurinkolaseissa',
           'pääkallo -> pieni hymy', 'nuutunut kukka -> kukkiva ruusu', 'klovni -> peukku ylös',
           'suru/nyrpeys -> ilo/hymy', 'särkynyt sydän -> ehjä sydän',
           'keskisormi -> rauhanmerkki'],
    'fr': ['larmes -> rire', 'pleurs -> sourire', 'suppliant -> cool avec des lunettes',
           'crâne -> léger sourire', 'fleur fanée -> rose épanouie', 'clown -> pouce levé',
           'tristesse/froncement -> joie/sourire', 'cœur brisé -> cœur entier',
           'majeur -> signe de paix'],
    'he': ['דמעות -> צחוק', 'בכי -> חיוך', 'מתחנן -> מגניב עם משקפי שמש',
           'גולגולת -> חיוך קל', 'פרח נבול -> ורד פורח', 'ליצן -> אגודל למעלה',
           'עצב/קימוט מצח -> שמחה/חיוך', 'לב שבור -> לב שלם', 'אצבע משולשת -> סמל השלום'],
    'hi': ['आँसू -> हँसी', 'रोना -> मुस्कान', 'विनती करता -> धूप के चश्मे में स्मार्ट',
           'खोपड़ी -> हल्की मुस्कान', 'मुरझाया फूल -> खिला गुलाब', 'जोकर -> अंगूठा ऊपर',
           'उदास/भौंह चढ़ाना -> खुशी/मुस्कान', 'टूटा दिल -> साबुत दिल',
           'बीच की ऊँगली -> शांति का चिह्न'],
    'hr': ['suze -> smijeh', 'plać -> osmijeh', 'molećiv -> faca sa sunčanim naočalama',
           'lubanja -> blagi osmijeh', 'uvenuli cvijet -> procvjetala ruža', 'klaun -> palac gore',
           'tuga/namrštenost -> radost/osmijeh', 'slomljeno srce -> cijelo srce',
           'srednji prst -> znak mira'],
    'hu': ['könnyek -> nevetés', 'sírás -> mosoly', 'könyörgő -> menő napszemüvegben',
           'koponya -> halvány mosoly', 'hervadt virág -> virágzó rózsa',
           'bohóc -> felfelé mutató hüvelykujj', 'szomorúság/homlokráncolás -> öröm/mosoly',
           'összetört szív -> ép szív', 'középső ujj -> békajel'],
    'id': ['air mata -> tawa', 'tangis -> senyum', 'memohon -> keren pakai kacamata',
           'tengkorak -> senyum tipis', 'bunga layu -> mawar mekar', 'badut -> jempol ke atas',
           'sedih/cemberut -> senang/senyum', 'patah hati -> hati utuh',
           'jari tengah -> tanda damai'],
    'it': ['lacrime -> risata', 'pianto -> sorriso', 'supplichevole -> figo con gli occhiali',
           'teschio -> leggero sorriso', 'fiore appassito -> rosa sbocciata', 'clown -> pollice in su',
           'tristezza/cipiglio -> gioia/sorriso', 'cuore spezzato -> cuore intero',
           'dito medio -> segno di pace'],
    'ja': ['涙 -> 笑い', '泣き顔 -> 笑顔', 'お願い -> サングラスでクール', 'どくろ -> 薄い笑み',
           'しおれた花 -> 咲いたバラ', 'ピエロ -> 親指を上げる', '悲しい/渋い顔 -> 喜び/笑顔',
           '割れたハート -> 完全なハート', '中指 -> ピースサイン'],
    'ko': ['눈물 -> 웃음', '우는 얼굴 -> 미소', '애원 -> 선글라스 낀 멋짐', '해골 -> 옅은 미소',
           '시든 꽃 -> 핀 장미', '광대 -> 엄지 척', '슬픔/찡그림 -> 기쁨/미소',
           '깨진 하트 -> 온전한 하트', '가운뎃손가락 -> 평화 기호'],
    'nl': ['tranen -> lachen', 'huilen -> glimlach', 'smekend -> cool met zonnebril',
           'schedel -> lichte glimlach', 'verwelkte bloem -> bloeiende roos', 'clown -> duim omhoog',
           'verdriet/fronsen -> blijheid/glimlach', 'gebroken hart -> heel hart',
           'middelvinger -> vredesteken'],
    'no': ['tårer -> latter', 'gråt -> smil', 'bønnfallende -> kul med solbriller',
           'hodeskalle -> lett smil', 'visnet blomst -> blomstrende rose', 'klovn -> tommel opp',
           'trist/rynket -> glede/smil', 'knust hjerte -> helt hjerte',
           'langfinger -> fredstegn'],
    'pl': ['łzy -> śmiech', 'płacz -> uśmiech', 'błagający -> cool w okularach',
           'czaszka -> lekki uśmiech', 'zwiędły kwiat -> rozkwitła róża', 'klaun -> kciuk w górę',
           'smutek/zmarszczenie -> radość/uśmiech', 'złamane serce -> całe serce',
           'środkowy palec -> znak pokoju'],
    'pt': ['lágrimas -> riso', 'choro -> sorriso', 'suplicante -> estiloso de óculos',
           'caveira -> leve sorriso', 'flor murcha -> rosa florida', 'palhaço -> joinha',
           'tristeza/cenho -> alegria/sorriso', 'coração partido -> coração inteiro',
           'dedo médio -> sinal de paz'],
    'ro': ['lacrimi -> râs', 'plâns -> zâmbet', 'rugăminte -> cool cu ochelari',
           'craniu -> zâmbet ușor', 'floare ofilită -> trandafir înflorit',
           'clovn -> degetul mare în sus', 'tristețe/încruntare -> bucurie/zâmbet',
           'inimă frântă -> inimă întreagă', 'deget mijlociu -> semnul păcii'],
    'sk': ['slzy -> smiech', 'plač -> úsmev', 'prosebný -> frajer v okuliaroch',
           'lebka -> ľahký úsmev', 'zvädnutá kvetina -> rozkvitnutá ruža', 'klaun -> palec nahor',
           'smútok/mračenie -> radosť/úsmev', 'zlomené srdce -> celé srdce',
           'prostredník -> znamenie mieru'],
    'sv': ['tårar -> skratt', 'gråt -> leende', 'bönfallande -> cool med solglasögon',
           'dödskalle -> litet leende', 'vissnad blomma -> blommande ros', 'clown -> tummen upp',
           'ledsen/rynkad panna -> glädje/leende', 'brustet hjärta -> helt hjärta',
           'långfinger -> fredstecken'],
    'th': ['น้ำตา -> หัวเราะ', 'ร้องไห้ -> ยิ้ม', 'อ้อนวอน -> เท่ใส่แว่นกันแดด',
           'กะโหลก -> ยิ้มบาง ๆ', 'ดอกไม้เหี่ยว -> กุหลาบบาน', 'ตัวตลก -> ชูนิ้วโป้ง',
           'เศร้า/หน้าบึ้ง -> ดีใจ/ยิ้ม', 'หัวใจแตกสลาย -> หัวใจสมบูรณ์',
           'นิ้วกลาง -> สัญลักษณ์สันติภาพ'],
    'tr': ['gözyaşları -> kahkaha', 'ağlama -> gülümseme', 'yalvaran -> güneş gözlüklü havalı',
           'kuru kafa -> hafif gülümseme', 'solmuş çiçek -> açmış gül',
           'palyaço -> başparmak yukarı', 'üzgün/kaş çatma -> neşe/gülümseme',
           'kırık kalp -> sağlam kalp', 'orta parmak -> barış işareti'],
    'uk': ['сльози -> сміх', 'плач -> усмішка', 'благальний -> крутий в окулярах',
           'череп -> легка усмішка', 'зів’яла квітка -> розквітла троянда',
           'клоун -> палець угору', 'смуток/похмурість -> радість/усмішка',
           'розбите серце -> ціле серце', 'середній палець -> знак миру'],
    'vi': ['nước mắt -> tiếng cười', 'khóc -> mỉm cười', 'van xin -> ngầu với kính râm',
           'đầu lâu -> cười nhẹ', 'hoa héo -> hoa hồng nở', 'chú hề -> giơ ngón cái',
           'buồn/nhăn mặt -> vui vẻ/mỉm cười', 'tim tan vỡ -> tim nguyên vẹn',
           'ngón giữa -> dấu hiệu hòa bình'],
    'zh': ['眼泪 -> 大笑', '哭脸 -> 微笑', '恳求 -> 戴墨镜很酷', '骷髅 -> 浅浅一笑',
           '枯萎的花 -> 盛开的玫瑰', '小丑 -> 竖起大拇指', '悲伤/皱眉 -> 高兴/微笑',
           '心碎 -> 完整的心', '中指 -> 和平手势'],
}
