# saitranslate scratch: batch A of 3 (locales ar, bg, cs, da, de, el, es, fi, fr, he)
# Values for the 18 keys that en.json gained after the last package (BetterDiscord tab).
# The three long descriptions are given as LOGICAL LINES; the applier joins them with
# the exact separator en.json uses (\r\r\n), so the source's line structure is preserved.

TRANS = {
    'ar': {
        'TabThemes': 'السمات والتطبيقات',
        'TabBetterDiscord': 'إضافات BetterDiscord',
        'BdPlugins': 'إضافات BETTERDISCORD',
        'BdInstallSelected': 'تطبيق / تثبيت',
        'BdUninstallSelected': 'إلغاء التثبيت',
        'BdOpenFolder': 'مجلد الإضافات',
        'BdRefresh': 'تحديث',
        'BdAvailablePlugins': 'الإضافات المتاحة',
        'BdPluginInfo': 'معلومات الإضافة',
        'BdLog': 'السجل',
        'BdInstalled': 'مثبّت',
        'BdAvailable': 'متاح',
        'BdStatusReady': 'مسار إضافات BetterDiscord: {0} (جاهز)',
        'BdStatusNotFound': 'لم يتم العثور على مجلد إضافات BetterDiscord: {0}',
        'BdStatusRefreshed': 'تم تحديث حالة إضافات BetterDiscord.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'يستبدل الرموز الباكية والحزينة والسامة برموز مبهجة ومضحكة:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'يراقب الرسائل والتفاعلات وأصول Twemoji ديناميكيًا عبر MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'يعطّل ويزيل الملصقات في Discord بالكامل:',
            '  - يخفي عرض الملصقات في رسائل الدردشة',
            '  - يخفي زر منتقي الملصقات من شريط الإدخال',
            '  - يخفي الملصقات من اقتراحات الإكمال التلقائي',
            '  - يطوي تلقائيًا صفوف الرسائل الفارغة التي تحتوي على ملصقات فقط',
            '',
            'يستخدم حقن CSS بلا زمن انتقال عبر BdApi.DOM.addStyle ومنظّف DOM نشط.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'يعطّل ويزيل جميع صور GIF في Discord بالكامل:',
            '  - يخفي صور GIF والفيديو ومعاينات التشغيل التلقائي في الدردشة',
            '  - يخفي زر GIF من شريط الإدخال',
            '  - يخفي تبويبات GIF في منتقي التعبيرات',
            '  - يخفي تضمينات Tenor و Giphy',
            '  - يطوي تلقائيًا صفوف الرسائل الفارغة التي تحتوي على GIF فقط',
            '',
            'يستخدم حقن CSS بلا زمن انتقال عبر BdApi.DOM.addStyle ومنظّف DOM نشط.',
        ],
    },
    'bg': {
        'TabThemes': 'Теми и приложения',
        'TabBetterDiscord': 'Добавки за BetterDiscord',
        'BdPlugins': 'BETTERDISCORD ДОБАВКИ',
        'BdInstallSelected': 'ПРИЛОЖИ / ИНСТАЛИРАЙ',
        'BdUninstallSelected': 'ДЕИНСТАЛИРАЙ',
        'BdOpenFolder': 'ПАПКА С ДОБАВКИ',
        'BdRefresh': 'ОБНОВИ',
        'BdAvailablePlugins': 'НАЛИЧНИ ДОБАВКИ',
        'BdPluginInfo': 'ИНФО ЗА ДОБАВКАТА',
        'BdLog': 'ДНЕВНИК',
        'BdInstalled': 'Инсталирани',
        'BdAvailable': 'Налични',
        'BdStatusReady': 'Път до добавките на BetterDiscord: {0} (Готово)',
        'BdStatusNotFound': 'Папката с добавки на BetterDiscord не е намерена: {0}',
        'BdStatusRefreshed': 'Състоянието на добавките на BetterDiscord е обновено.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Заменя плачещите, тъжните и токсичните емоджита с радостни и смешни:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Следи динамично съобщения, реакции и ресурси на Twemoji чрез MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Напълно изключва и премахва стикерите в Discord:',
            '  - Скрива изобразяването на стикери в съобщенията',
            '  - Скрива бутона за стикери от лентата за въвеждане',
            '  - Скрива стикерите от предложенията за автодовършване',
            '  - Автоматично свива празните редове, съдържащи само стикери',
            '',
            'Използва CSS инжекция без закъснение чрез BdApi.DOM.addStyle и активен почистващ механизъм на DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Напълно изключва и премахва всички GIF файлове в Discord:',
            '  - Скрива GIF изображения, видеа и прегледи с автоматично възпроизвеждане в чата',
            '  - Скрива бутона за GIF от лентата за въвеждане',
            '  - Скрива разделите за GIF в избора на изрази',
            '  - Скрива вградените материали от Tenor и Giphy',
            '  - Автоматично свива празните редове, съдържащи само GIF файлове',
            '',
            'Използва CSS инжекция без закъснение чрез BdApi.DOM.addStyle и активен почистващ механизъм на DOM.',
        ],
    },
    'cs': {
        'TabThemes': 'Motivy a aplikace',
        'TabBetterDiscord': 'Pluginy BetterDiscord',
        'BdPlugins': 'PLUGINY BETTERDISCORD',
        'BdInstallSelected': 'POUŽÍT / NAINSTALOVAT',
        'BdUninstallSelected': 'ODINSTALOVAT',
        'BdOpenFolder': 'SLOŽKA PLUGINŮ',
        'BdRefresh': 'OBNOVIT',
        'BdAvailablePlugins': 'DOSTUPNÉ PLUGINY',
        'BdPluginInfo': 'INFORMACE O PLUGINU',
        'BdLog': 'ZÁZNAM',
        'BdInstalled': 'Nainstalované',
        'BdAvailable': 'Dostupné',
        'BdStatusReady': 'Cesta k pluginům BetterDiscord: {0} (Připraveno)',
        'BdStatusNotFound': 'Složka pluginů BetterDiscord nebyla nalezena: {0}',
        'BdStatusRefreshed': 'Stav pluginů BetterDiscord byl obnoven.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Nahrazuje plačící, smutné a toxické emoji veselými a vtipnými:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Dynamicky sleduje zprávy, reakce a podklady Twemoji pomocí MutationObserveru.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Úplně vypíná a odstraňuje samolepky v Discordu:',
            '  - Skrývá vykreslování samolepek ve zprávách',
            '  - Skrývá tlačítko samolepek na vstupním panelu',
            '  - Skrývá samolepky z našeptávače',
            '  - Automaticky sbalí prázdné řádky obsahující jen samolepky',
            '',
            'Používá injektáž CSS bez latence přes BdApi.DOM.addStyle a aktivní čistič DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Úplně vypíná a odstraňuje všechny GIFy v Discordu:',
            '  - Skrývá obrázky a videa GIF i náhledy s automatickým přehráváním v chatu',
            '  - Skrývá tlačítko GIF na vstupním panelu',
            '  - Skrývá záložky GIF ve výběru výrazů',
            '  - Skrývá vložené obsahy Tenor a Giphy',
            '  - Automaticky sbalí prázdné řádky obsahující jen GIFy',
            '',
            'Používá injektáž CSS bez latence přes BdApi.DOM.addStyle a aktivní čistič DOM.',
        ],
    },
    'da': {
        'TabThemes': 'Temaer og apps',
        'TabBetterDiscord': 'BetterDiscord-plugins',
        'BdPlugins': 'BETTERDISCORD-PLUGINS',
        'BdInstallSelected': 'ANVEND / INSTALLER',
        'BdUninstallSelected': 'AFINSTALLER',
        'BdOpenFolder': 'PLUGIN-MAPPE',
        'BdRefresh': 'OPDATER',
        'BdAvailablePlugins': 'TILGÆNGELIGE PLUGINS',
        'BdPluginInfo': 'PLUGIN-INFO',
        'BdLog': 'LOG',
        'BdInstalled': 'Installeret',
        'BdAvailable': 'Tilgængelig',
        'BdStatusReady': 'Sti til BetterDiscord-plugins: {0} (Klar)',
        'BdStatusNotFound': 'Mappen med BetterDiscord-plugins blev ikke fundet: {0}',
        'BdStatusRefreshed': 'Status for BetterDiscord-plugins er opdateret.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Erstatter grædende, triste og giftige emojis med glade og sjove:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Overvåger beskeder, reaktioner og Twemoji-aktiver dynamisk via MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Slår helt fra og fjerner klistermærker i Discord:',
            '  - Skjuler klistermærker i chatbeskeder',
            '  - Skjuler klistermærkeknappen i inputlinjen',
            '  - Skjuler klistermærker i autofuldførelsesforslag',
            '  - Klapper tomme rækker med kun klistermærker sammen automatisk',
            '',
            'Bruger CSS-injektion uden forsinkelse via BdApi.DOM.addStyle og en aktiv DOM-oprydder.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            "Slår helt fra og fjerner alle GIF'er i Discord:",
            '  - Skjuler GIF-billeder, videoer og autoafspilningsforhåndsvisninger i chatten',
            '  - Skjuler GIF-knappen i inputlinjen',
            '  - Skjuler GIF-faner i udtryksvælgeren',
            '  - Skjuler Tenor- og Giphy-indlejringer',
            "  - Klapper tomme rækker med kun GIF'er sammen automatisk",
            '',
            'Bruger CSS-injektion uden forsinkelse via BdApi.DOM.addStyle og en aktiv DOM-oprydder.',
        ],
    },
    'de': {
        'TabThemes': 'Themes & Apps',
        'TabBetterDiscord': 'BetterDiscord-Plugins',
        'BdPlugins': 'BETTERDISCORD-PLUGINS',
        'BdInstallSelected': 'ANWENDEN / INSTALLIEREN',
        'BdUninstallSelected': 'DEINSTALLIEREN',
        'BdOpenFolder': 'PLUGIN-ORDNER',
        'BdRefresh': 'AKTUALISIEREN',
        'BdAvailablePlugins': 'VERFÜGBARE PLUGINS',
        'BdPluginInfo': 'PLUGIN-INFO',
        'BdLog': 'PROTOKOLL',
        'BdInstalled': 'Installiert',
        'BdAvailable': 'Verfügbar',
        'BdStatusReady': 'Pfad zu den BetterDiscord-Plugins: {0} (Bereit)',
        'BdStatusNotFound': 'BetterDiscord-Plugin-Ordner nicht gefunden: {0}',
        'BdStatusRefreshed': 'Status der BetterDiscord-Plugins aktualisiert.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Ersetzt weinende, traurige und toxische Emojis durch fröhliche und lustige:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Überwacht Nachrichten, Reaktionen und Twemoji-Assets dynamisch per MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Deaktiviert und entfernt Sticker in Discord vollständig:',
            '  - Blendet Sticker-Darstellungen in Chat-Nachrichten aus',
            '  - Blendet die Sticker-Schaltfläche aus der Eingabeleiste aus',
            '  - Blendet Sticker aus den Vorschlägen der Autovervollständigung aus',
            '  - Klappt leere Nachrichtenzeilen, die nur Sticker enthalten, automatisch ein',
            '',
            'Nutzt CSS-Injektion ohne Latenz über BdApi.DOM.addStyle und einen aktiven DOM-Aufräumer.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Deaktiviert und entfernt alle GIFs in Discord vollständig:',
            '  - Blendet GIF-Bilder, Videos und Autoplay-Vorschauen im Chat aus',
            '  - Blendet die GIF-Schaltfläche aus der Eingabeleiste aus',
            '  - Blendet GIF-Reiter im Ausdrucks-Auswähler aus',
            '  - Blendet Tenor- und Giphy-Einbettungen aus',
            '  - Klappt leere Nachrichtenzeilen, die nur GIFs enthalten, automatisch ein',
            '',
            'Nutzt CSS-Injektion ohne Latenz über BdApi.DOM.addStyle und einen aktiven DOM-Aufräumer.',
        ],
    },
    'el': {
        'TabThemes': 'Θέματα και εφαρμογές',
        'TabBetterDiscord': 'Πρόσθετα BetterDiscord',
        'BdPlugins': 'ΠΡΟΣΘΕΤΑ BETTERDISCORD',
        'BdInstallSelected': 'ΕΦΑΡΜΟΓΗ / ΕΓΚΑΤΑΣΤΑΣΗ',
        'BdUninstallSelected': 'ΑΠΕΓΚΑΤΑΣΤΑΣΗ',
        'BdOpenFolder': 'ΦΑΚΕΛΟΣ ΠΡΟΣΘΕΤΩΝ',
        'BdRefresh': 'ΑΝΑΝΕΩΣΗ',
        'BdAvailablePlugins': 'ΔΙΑΘΕΣΙΜΑ ΠΡΟΣΘΕΤΑ',
        'BdPluginInfo': 'ΠΛΗΡΟΦΟΡΙΕΣ ΠΡΟΣΘΕΤΟΥ',
        'BdLog': 'ΑΡΧΕΙΟ ΚΑΤΑΓΡΑΦΗΣ',
        'BdInstalled': 'Εγκατεστημένα',
        'BdAvailable': 'Διαθέσιμα',
        'BdStatusReady': 'Διαδρομή πρόσθετων BetterDiscord: {0} (Έτοιμο)',
        'BdStatusNotFound': 'Ο φάκελος πρόσθετων του BetterDiscord δεν βρέθηκε: {0}',
        'BdStatusRefreshed': 'Η κατάσταση των πρόσθετων BetterDiscord ανανεώθηκε.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Αντικαθιστά τα κλαψιάρικα, λυπημένα και τοξικά emoji με χαρούμενα και αστεία:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Παρακολουθεί δυναμικά μηνύματα, αντιδράσεις και πόρους Twemoji μέσω MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Απενεργοποιεί και αφαιρεί πλήρως τα αυτοκόλλητα στο Discord:',
            '  - Κρύβει την εμφάνιση αυτοκόλλητων στα μηνύματα',
            '  - Κρύβει το κουμπί αυτοκόλλητων από τη γραμμή εισαγωγής',
            '  - Κρύβει τα αυτοκόλλητα από τις προτάσεις αυτόματης συμπλήρωσης',
            '  - Συμπτύσσει αυτόματα κενές γραμμές μηνυμάτων με μόνο αυτοκόλλητα',
            '',
            'Χρησιμοποιεί έγχυση CSS χωρίς καθυστέρηση μέσω BdApi.DOM.addStyle και ενεργό καθαριστή DOM.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Απενεργοποιεί και αφαιρεί πλήρως όλα τα GIF στο Discord:',
            '  - Κρύβει εικόνες και βίντεο GIF και τις προεπισκοπήσεις αυτόματης αναπαραγωγής στη συνομιλία',
            '  - Κρύβει το κουμπί GIF από τη γραμμή εισαγωγής',
            '  - Κρύβει τις καρτέλες GIF στον επιλογέα εκφράσεων',
            '  - Κρύβει τις ενσωματώσεις Tenor και Giphy',
            '  - Συμπτύσσει αυτόματα κενές γραμμές μηνυμάτων με μόνο GIF',
            '',
            'Χρησιμοποιεί έγχυση CSS χωρίς καθυστέρηση μέσω BdApi.DOM.addStyle και ενεργό καθαριστή DOM.',
        ],
    },
    'es': {
        'TabThemes': 'Temas y aplicaciones',
        'TabBetterDiscord': 'Complementos de BetterDiscord',
        'BdPlugins': 'COMPLEMENTOS DE BETTERDISCORD',
        'BdInstallSelected': 'APLICAR / INSTALAR',
        'BdUninstallSelected': 'DESINSTALAR',
        'BdOpenFolder': 'CARPETA DE COMPLEMENTOS',
        'BdRefresh': 'ACTUALIZAR',
        'BdAvailablePlugins': 'COMPLEMENTOS DISPONIBLES',
        'BdPluginInfo': 'INFORMACIÓN DEL COMPLEMENTO',
        'BdLog': 'REGISTRO',
        'BdInstalled': 'Instalados',
        'BdAvailable': 'Disponibles',
        'BdStatusReady': 'Ruta de los complementos de BetterDiscord: {0} (Listo)',
        'BdStatusNotFound': 'No se encontró la carpeta de complementos de BetterDiscord: {0}',
        'BdStatusRefreshed': 'Estado de los complementos de BetterDiscord actualizado.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Reemplaza los emojis llorones, tristes y tóxicos por otros alegres y divertidos:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Vigila dinámicamente mensajes, reacciones y recursos de Twemoji mediante MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Desactiva y elimina por completo los stickers de Discord:',
            '  - Oculta los stickers en los mensajes del chat',
            '  - Oculta el botón de stickers de la barra de entrada',
            '  - Oculta los stickers de las sugerencias de autocompletado',
            '  - Contrae automáticamente las filas vacías que solo tienen stickers',
            '',
            'Usa inyección de CSS sin latencia mediante BdApi.DOM.addStyle y un limpiador de DOM activo.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Desactiva y elimina por completo todos los GIF de Discord:',
            '  - Oculta imágenes y vídeos GIF y las vistas previas con reproducción automática en el chat',
            '  - Oculta el botón de GIF de la barra de entrada',
            '  - Oculta las pestañas de GIF en el selector de expresiones',
            '  - Oculta las incrustaciones de Tenor y Giphy',
            '  - Contrae automáticamente las filas vacías que solo tienen GIF',
            '',
            'Usa inyección de CSS sin latencia mediante BdApi.DOM.addStyle y un limpiador de DOM activo.',
        ],
    },
    'fi': {
        'TabThemes': 'Teemat ja sovellukset',
        'TabBetterDiscord': 'BetterDiscord-lisäosat',
        'BdPlugins': 'BETTERDISCORD-LISÄOSAT',
        'BdInstallSelected': 'KÄYTÄ / ASENNA',
        'BdUninstallSelected': 'POISTA ASENNUS',
        'BdOpenFolder': 'LISÄOSAKANSIO',
        'BdRefresh': 'PÄIVITÄ',
        'BdAvailablePlugins': 'SAATAVILLA OLEVAT LISÄOSAT',
        'BdPluginInfo': 'LISÄOSAN TIEDOT',
        'BdLog': 'LOKI',
        'BdInstalled': 'Asennettu',
        'BdAvailable': 'Saatavilla',
        'BdStatusReady': 'BetterDiscord-lisäosien polku: {0} (Valmis)',
        'BdStatusNotFound': 'BetterDiscordin lisäosakansiota ei löytynyt: {0}',
        'BdStatusRefreshed': 'BetterDiscord-lisäosien tila päivitetty.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Korvaa itkevät, surulliset ja myrkylliset emojit iloisilla ja hauskoilla:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Seuraa viestejä, reaktioita ja Twemoji-aineistoja dynaamisesti MutationObserverin avulla.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Kytkee pois ja poistaa Discordin tarrat kokonaan:',
            '  - Piilottaa tarrojen piirron chat-viesteistä',
            '  - Piilottaa tarrapainikkeen syöttöpalkista',
            '  - Piilottaa tarrat automaattisen täydennyksen ehdotuksista',
            '  - Kutistaa automaattisesti tyhjät rivit, joissa on vain tarroja',
            '',
            'Käyttää viiveetöntä CSS-injektiota BdApi.DOM.addStylen kautta ja aktiivista DOM-siivoojaa.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Kytkee pois ja poistaa kaikki Discordin GIFit kokonaan:',
            '  - Piilottaa GIF-kuvat, videot ja automaattisen toiston esikatselut chatissa',
            '  - Piilottaa GIF-painikkeen syöttöpalkista',
            '  - Piilottaa GIF-välilehdet ilmaisujen valitsimesta',
            '  - Piilottaa Tenorin ja Giphyn upotukset',
            '  - Kutistaa automaattisesti tyhjät rivit, joissa on vain GIFejä',
            '',
            'Käyttää viiveetöntä CSS-injektiota BdApi.DOM.addStylen kautta ja aktiivista DOM-siivoojaa.',
        ],
    },
    'fr': {
        'TabThemes': 'Thèmes et applications',
        'TabBetterDiscord': 'Plugins BetterDiscord',
        'BdPlugins': 'PLUGINS BETTERDISCORD',
        'BdInstallSelected': 'APPLIQUER / INSTALLER',
        'BdUninstallSelected': 'DÉSINSTALLER',
        'BdOpenFolder': 'DOSSIER DES PLUGINS',
        'BdRefresh': 'ACTUALISER',
        'BdAvailablePlugins': 'PLUGINS DISPONIBLES',
        'BdPluginInfo': 'INFOS DU PLUGIN',
        'BdLog': 'JOURNAL',
        'BdInstalled': 'Installés',
        'BdAvailable': 'Disponibles',
        'BdStatusReady': 'Chemin des plugins BetterDiscord : {0} (Prêt)',
        'BdStatusNotFound': 'Dossier des plugins BetterDiscord introuvable : {0}',
        'BdStatusRefreshed': 'État des plugins BetterDiscord actualisé.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'Remplace les emojis larmoyants, tristes et toxiques par des emojis joyeux et drôles :',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'Surveille dynamiquement les messages, les réactions et les ressources Twemoji via MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'Désactive et supprime complètement les stickers de Discord :',
            '  - Masque les stickers dans les messages du chat',
            '  - Masque le bouton des stickers dans la barre de saisie',
            '  - Masque les stickers dans les suggestions de l’autocomplétion',
            '  - Replie automatiquement les lignes vides ne contenant que des stickers',
            '',
            'Utilise une injection CSS sans latence via BdApi.DOM.addStyle et un nettoyeur DOM actif.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'Désactive et supprime complètement tous les GIF de Discord :',
            '  - Masque les images et vidéos GIF ainsi que les aperçus à lecture automatique dans le chat',
            '  - Masque le bouton GIF dans la barre de saisie',
            '  - Masque les onglets GIF dans le sélecteur d’expressions',
            '  - Masque les intégrations Tenor et Giphy',
            '  - Replie automatiquement les lignes vides ne contenant que des GIF',
            '',
            'Utilise une injection CSS sans latence via BdApi.DOM.addStyle et un nettoyeur DOM actif.',
        ],
    },
    'he': {
        'TabThemes': 'ערכות נושא ויישומים',
        'TabBetterDiscord': 'תוספי BetterDiscord',
        'BdPlugins': 'תוספי BETTERDISCORD',
        'BdInstallSelected': 'החל / התקן',
        'BdUninstallSelected': 'הסר התקנה',
        'BdOpenFolder': 'תיקיית התוספים',
        'BdRefresh': 'רענן',
        'BdAvailablePlugins': 'תוספים זמינים',
        'BdPluginInfo': 'מידע על התוסף',
        'BdLog': 'יומן',
        'BdInstalled': 'מותקנים',
        'BdAvailable': 'זמינים',
        'BdStatusReady': 'נתיב תוספי BetterDiscord: {0} (מוכן)',
        'BdStatusNotFound': 'תיקיית התוספים של BetterDiscord לא נמצאה: {0}',
        'BdStatusRefreshed': 'מצב תוספי BetterDiscord רוענן.',
        'BdGoodEmojiDesc': [
            'GoodEmoji v1.0.0 (Wintage)', '',
            'מחליף אימוג׳ים בוכיים, עצובים ורעילים באימוג׳ים שמחים ומצחיקים:',
            '  - sob -> joy', '  - cry -> smile', '  - pleading -> sunglasses',
            '  - skull -> slight_smile', '  - wilted_rose -> rose', '  - clown -> thumbsup',
            '  - sad/frown -> smiley/grin', '  - broken_heart -> heart', '  - middle_finger -> peace',
            '',
            'עוקב באופן דינמי אחרי הודעות, תגובות ונכסי Twemoji באמצעות MutationObserver.',
        ],
        'BdRemoveStickersDesc': [
            'RemoveStickers v1.0.0 (Wintage)', '',
            'משבית ומסיר לחלוטין מדבקות ב-Discord:',
            '  - מסתיר את הצגת המדבקות בהודעות הצ׳אט',
            '  - מסתיר את כפתור המדבקות משורת הקלט',
            '  - מסתיר מדבקות מהצעות ההשלמה האוטומטית',
            '  - מקפל אוטומטית שורות ריקות שמכילות מדבקות בלבד',
            '',
            'משתמש בהזרקת CSS ללא השהיה דרך BdApi.DOM.addStyle ובמנקה DOM פעיל.',
        ],
        'BdRemoveGIFSDesc': [
            'RemoveGIFS v1.0.0 (Wintage)', '',
            'משבית ומסיר לחלוטין את כל קובצי ה-GIF ב-Discord:',
            '  - מסתיר תמונות וסרטוני GIF ותצוגות מקדימות עם הפעלה אוטומטית בצ׳אט',
            '  - מסתיר את כפתור ה-GIF משורת הקלט',
            '  - מסתיר לשוניות GIF בבורר הביטויים',
            '  - מסתיר הטמעות של Tenor ו-Giphy',
            '  - מקפל אוטומטית שורות ריקות שמכילות קובצי GIF בלבד',
            '',
            'משתמש בהזרקת CSS ללא השהיה דרך BdApi.DOM.addStyle ובמנקה DOM פעיל.',
        ],
    },
}
