# saitranslate scratch: desktop/README.md delta, batch 1 of 3 (ar, bg, cs, da, de, el, es, fi, fr, he)
# Source: desktop/README.md normalized sha256 b77c16d423936045 (was 1b166ae6a7cf8a5c).
# Technical tokens stay byte-identical; prose is translated.
# 'q' = the 4 paragraphs of "### qBittorrent", 'f' = the 4 of the Fonts section.

DOC = {
    'ar': {
        'fonts_head': '### الخطوط: تُذكر بالأسماء، ولا تُثبَّت أبدًا',
        'q': [
            'يكتب `qbittorrent` سمة واجهة Qt **غير محزَّمة** في `%APPDATA%\\qBittorrent\\themes\\wintage` — ملف `config.json` (أدوار `Palette.*` إضافةً إلى ألوان السياق الخاصة بـ qBittorrent: حالات قائمة النقل، وشدّة سجل الأحداث) وملف `stylesheet.qss` بجانبه (الحواف المشطوفة بسماكة 2px والزوايا القائمة وخط Verdana، وهي أمور لا تستطيع لوحة الألوان التعبير عنها) — ثم يوجّه `General\\CustomUIThemePath` إلى ملف `config.json` ذاك ويضبط `General\\UseCustomUITheme=true`.',
            'اخترنا الصيغة غير المحزَّمة عمدًا بدل حزمة `.qbtheme`: فملف `.qbtheme` هو ملف Qt Resource Collection ويحتاج إلى ملف `rcc` التنفيذي بإصدار رئيسي مطابق لإنشائه، أي اعتماد على مصرف برمجي مقابل ملفَّي نص فقط. أما qBittorrent فيقرأ صيغة المجلد أصليًّا (`FolderThemeSource`).',
            'أغلق qBittorrent قبل Apply أو Revert: فهو يعيد كتابة `qBittorrent.ini` بالكامل عند الخروج، لذا يضيع عند الإغلاق أي تعديل أُجري أثناء تشغيله — لذلك يرفض الهدف العمل في تلك الحالة بدل الإبلاغ عن نجاح يمحوه الخروج التالي. ويعيد `-Revert` مفتاحَي INI إلى قيمهما الدقيقة السابقة لـ Wintage (أو يحذفهما إن لم تكونا موجودتين)، ويعيد أي مجلد سمة بالاسم نفسه بايتًا ببايت؛ أما تعديلات `qBittorrent.ini` غير المتعلقة به والمنفَّذة بعد Apply فتبقى.',
            'غير متاح: أيقونات شريط الأدوات وصينية النظام تأتي من حزمة موارد qBittorrent المصرَّفة، فتبقى بألوانها الأصلية.',
        ],
        'f': [
            'يطلب القانون الأول في UI.md خط Verdana **بلا تنعيم حواف**. ولا توجد في ورقة أنماط Qt خاصة لهذا، و`OSDFont` في MPC-HC ليس سوى اسم محرف GDI — فالرافعة الوحيدة هي المحرف نفسه. و`Verdana_m1.ttf` في جذر المستودع هو نسخة من Verdana تحمل ضربات نقطية 1bpp مُصيَّرة مسبقًا بقياسات 3–30 ppem، يستعملها المُصيِّر بدل تنعيم المخطط التفصيلي.',
            'تسمّي أوراق أنماط `qbittorrent` و`obs` الخط `Verdana_m1, Verdana`، ويسمّي `mpchc` أيَّهما يحلّه الجهاز فعليًا. **والمثبِّت لا يثبّت خطًّا ولا يزيله أبدًا**، وذلك مقصود لا ناقص:',
            'تُحلّ عائلة الخطوط حسب (العائلة، النمط). فسجّل Regular و Bold و Italic ليحلّها كل مستهلك بشكل صحيح؛ وألغِ تسجيل **عضو واحد** لتُعاد كل الحالات التي تطلب تلك العائلة إلى عضو باقٍ. وعلى جهاز يربط `MS Shell Dlg 2` — خط حوارات Windows — بتلك العائلة عبر `HKLM\\...\\FontSubstitutes`، فإن إزالة Regular تجعل **سطح المكتب كله مائلًا**، بما في ذلك عناوين النوافذ التي خزّنها DWM في الذاكرة المؤقتة، ولا سبيل لاستعادته إلا بتسجيل الخروج. ولا يُصلح ذلك أيّ عدّ مراجع: فمدى الضرر يمتد إلى الجهاز كله، وليس مثبِّت السمات موضعه.',
            'لذلك يبقى تركيب المحرف إجراءً صريحًا يقوم به المستخدم مرة واحدة: انقر بزر الفأرة الأيمن على `Verdana_m1.ttf` ← **Install** (للمستخدم الحالي، دون صلاحيات إدارية)، ثم أعد تطبيق الهدف. وإن كان المحرف غائبًا ذكرت الأهداف ذلك مرة واحدة، وسمّت الحل، وتراجعت إلى Verdana الأصلي — منعَّم الحواف، لكن لا شيء يُنفَّذ على الجهاز خلف ظهرك.',
        ],
    },
    'bg': {
        'fonts_head': '### Шрифтове: посочвани по име, никога инсталирани',
        'q': [
            '`qbittorrent` записва **разгъната** Qt тема за интерфейса в `%APPDATA%\\qBittorrent\\themes\\wintage` — файл `config.json` (ролите `Palette.*` плюс собствените контекстни цветове на qBittorrent: състояния в списъка с трансфери, степени на дневника) и до него `stylesheet.qss` (2px-овите фаски, правите ъгли и Verdana, които палитрата не може да изрази) — после насочва `General\\CustomUIThemePath` към този `config.json` и задава `General\\UseCustomUITheme=true`.',
            'Разгънато, а не като пакет `.qbtheme` — умишлено: `.qbtheme` е файл от тип Qt Resource Collection и за създаването му е нужен `rcc` изпълним файл със съвпадаща главна версия на машината, тоест зависимост от компилатор заради два текстови файла. qBittorrent чете папковата форма първоначално (`FolderThemeSource`).',
            'Затворете qBittorrent преди Apply или Revert: той пренаписва целия `qBittorrent.ini` при изход, така че направена при работещо приложение промяна се губи при затваряне — целта отказва да работи в това състояние, вместо да докладва успех, който следващият изход заличава. `-Revert` връща двата INI ключа към точните им стойности преди Wintage (или ги премахва, ако не са били налични) и връща всеки папков мотив със същото име байт по байт; несвързани промени в `qBittorrent.ini`, направени след Apply, остават.',
            'Недостижимо: иконите на лентата с инструменти и в системния трей идват от собствения компилиран ресурсен пакет на qBittorrent, затова те запазват обичайните си цветове.',
        ],
        'f': [
            'Първият закон в UI.md иска Verdana **без изглаждане на ръбовете**. Qt стилов лист няма свойство за това, а `OSDFont` на MPC-HC е просто име на GDI шрифт — единственият лост е самият шрифт. `Verdana_m1.ttf` в корена на хранилището е копие на Verdana с предварително изобразени 1bpp растерни щрихи при 3–30 ppem, които програмата за изобразяване предпочита пред изглаждането на контура.',
            'Стиловите листове на `qbittorrent` и `obs` посочват `Verdana_m1, Verdana`, а `mpchc` посочва онзи от двата, който машината действително разпознае. **Инсталаторът никога не инсталира и не деинсталира шрифт** и това е умишлено, а не недовършено:',
            'Шрифтовото семейство се разпознава по (семейство, стил). Регистрирайте Regular + Bold + Italic и всеки потребител ще го разпознае правилно; отпишете **един** член и всеки потребител, който иска това семейство, ще се пренасочи към останал член. На машина, която свързва `MS Shell Dlg 2` — диалоговия шрифт на Windows — с това семейство чрез `HKLM\\...\\FontSubstitutes`, премахването на Regular прави **целия работен плот наклонен**, включително заглавните ленти на прозорците, които DWM вече е кеширал, и за връщане е нужно излизане от профила. Никакво броене на препратки не решава това: обхватът е върху цялата машина и инсталатор на теми няма работа там.',
            'Затова шрифтът остава еднократно, изрично действие на потребителя: десен бутон върху `Verdana_m1.ttf` → **Install** (за текущия потребител, без администраторски права), после приложете целта отново. Ако шрифтът липсва, целите казват това веднъж, посочват решението и се връщат към стандартния Verdana — изгладен, но нищо не се прави на машината зад гърба ви.',
        ],
    },
    'cs': {
        'fonts_head': '### Písma: pojmenovaná, nikdy neinstalovaná',
        'q': [
            '`qbittorrent` zapisuje **rozbalený** Qt motiv rozhraní do `%APPDATA%\\qBittorrent\\themes\\wintage` — soubor `config.json` (role `Palette.*` plus vlastní kontextové barvy qBittorrentu: stavy seznamu přenosů, úrovně protokolu) a vedle něj `stylesheet.qss` (2px zkosení, pravé rohy a Verdana, což paleta vyjádřit neumí) — poté nasměruje `General\\CustomUIThemePath` na tento `config.json` a nastaví `General\\UseCustomUITheme=true`.',
            'Rozbaleně, a ne jako balíček `.qbtheme` — záměrně: `.qbtheme` je soubor typu Qt Resource Collection a k jeho vytvoření by na stroji bylo potřeba `rcc` se shodnou hlavní verzí, tedy závislost na kompilátoru kvůli dvěma textovým souborům. qBittorrent čte složkovou podobu nativně (`FolderThemeSource`).',
            'Před Apply nebo Revert qBittorrent zavřete: při ukončení přepisuje celý `qBittorrent.ini`, takže úprava provedená za běhu se při zavření zahodí — cíl v takovém stavu odmítne pracovat, místo aby hlásil úspěch, který příští ukončení smaže. `-Revert` vrátí dva klíče v INI na přesné hodnoty před Wintage (nebo je odstraní, pokud nebyly) a vrátí každou stejnojmennou složku motivu bajt po bajtu; nesouvisející úpravy `qBittorrent.ini` provedené po Apply zůstávají.',
            'Nedosažitelné: ikony panelu nástrojů a oznamovací oblasti pocházejí z vlastního zkompilovaného zdrojového balíčku qBittorrentu, takže si zachovávají původní barvy.',
        ],
        'f': [
            'První zákon v UI.md žádá Verdanu **bez vyhlazování**. Qt stylesheet pro to nemá vlastnost a `OSDFont` v MPC-HC je jen název GDI řezu — jedinou pákou je sám řez. `Verdana_m1.ttf` v kořeni repozitáře je kopie Verdanу s předvykreslenými 1bpp bitmapovými řezy při 3–30 ppem, které vykreslovací jádro použije před vyhlazením obrysu.',
            'Stylesheety `qbittorrent` a `obs` uvádějí `Verdana_m1, Verdana` a `mpchc` uvádí ten z obou, který stroj skutečně rozpozná. **Instalátor písmo nikdy nenainstaluje ani neodinstaluje**, a to je záměr, ne nedodělek:',
            'Rodina písma se rozlišuje podle (rodina, řez). Zaregistrujte Regular + Bold + Italic a každý spotřebitel ji rozpozná správně; odregistrujte **jeden** člen a každý spotřebitel žádající tuto rodinu se přesměruje na přeživší člen. Na stroji, který na tuto rodinu přes `HKLM\\...\\FontSubstitutes` aliasuje `MS Shell Dlg 2` — dialogové písmo Windows —, přepne odstranění Regularu **celou plochu do kurzívy**, včetně titulků oken, které má DWM už v cache, a zpět to vrátí jen odhlášení. Žádné počítání referencí to nespraví: dopad je v rámci celého stroje a instalační nástroj motivů tam nemá co dělat.',
            'Řez je tedy jednorázová, výslovná akce uživatele: klikněte pravým tlačítkem na `Verdana_m1.ttf` → **Install** (pro uživatele, bez správce), pak cíl znovu použijte. Pokud řez chybí, cíle to jednou řeknou, pojmenují řešení a vrátí se ke standardní Verdaně — vyhlazené, ale na stroji se nic neděje za vašimi zády.',
        ],
    },
    'da': {
        'fonts_head': '### Skrifttyper: navngivet, aldrig installeret',
        'q': [
            '`qbittorrent` skriver et **udpakket** Qt-uitema ned i `%APPDATA%\\qBittorrent\\themes\\wintage` — en `config.json` (rollerne `Palette.*` plus qBittorrents egne kontekstfarver: tilstande i overførselslisten, logalvorligheder) og en `stylesheet.qss` ved siden af (2px-fasningerne, de rette hjørner og Verdana, som en palet ikke kan udtrykke) — og peger derefter `General\\CustomUIThemePath` på den `config.json` og sætter `General\\UseCustomUITheme=true`.',
            'Udpakket frem for en `.qbtheme`-pakke, med vilje: en `.qbtheme` er en Qt Resource Collection-fil og ville kræve en `rcc`-binær med matchende major-version på maskinen for at blive lavet — en compilerafhængighed for to tekstfiler. qBittorrent læser mappeformen oprindeligt (`FolderThemeSource`).',
            'Luk qBittorrent før Apply eller Revert: den omskriver hele `qBittorrent.ini` ved afslutning, så en ændring foretaget mens den kører, kasseres ved lukning — målet nægter at køre i den tilstand frem for at rapportere en succes, som næste afslutning sletter. `-Revert` fører de to INI-nøgler tilbage til deres nøjagtige værdier før Wintage (eller fjerner dem, hvis de ikke fandtes) og lægger en eventuel temamappe med samme navn tilbage byte for byte; uvedkommende ændringer i `qBittorrent.ini` efter Apply overlever.',
            'Ikke muligt: værktøjslinje- og bakkeikoner kommer fra qBittorrents egen kompilerede ressourcepakke, så de beholder deres oprindelige farver.',
        ],
        'f': [
            'Første lov i UI.md kræver Verdana **uden kantudjævning**. Et Qt-stylesheet har ingen egenskab til det, og MPC-HCs `OSDFont` er blot et GDI-navn — den eneste håndtag er selve snittet. `Verdana_m1.ttf` i repoets rod er en kopi af Verdana med forudrenderede 1bpp-bitmapstørrelser ved 3–30 ppem, som en renderer bruger i stedet for at udjævne omridset.',
            'Stylesheetene `qbittorrent` og `obs` angiver `Verdana_m1, Verdana`, og `mpchc` angiver den af de to, maskinen faktisk opløser. **Installeren installerer eller afinstallerer aldrig en skrifttype**, og det er med vilje snarere end uafsluttet:',
            'En skriftfamilie opløses efter (familie, snit). Registrér Regular + Bold + Italic, og enhver forbruger opløser korrekt; afregistrér **ét** medlem, og enhver forbruger, der beder om den familie, peger i stedet på et overlevende medlem. På en maskine, der gennem `HKLM\\...\\FontSubstitutes` aliasser `MS Shell Dlg 2` — Windows\' dialogskrifttype — til den familie, får fjernelse af Regular **hele skrivebordet til at stå i kursiv**, inklusive vinduestitler, DWM allerede har cachet, og der kræves en logoff for at få det tilbage. Ingen refcounting løser det: skadesvidden er maskinomfattende, og en temainstallerer har intet der at gøre.',
            'Snittet er derfor en enkeltstående, udtrykkelig brugerhandling: højreklik på `Verdana_m1.ttf` → **Install** (pr. bruger, ingen administrator), og anvend derefter målet igen. Mangler snittet, siger målene det én gang, nævner løsningen og falder tilbage til standard-Verdana — kantudjævnet, men der gøres intet ved maskinen bag din ryg.',
        ],
    },
    'de': {
        'fonts_head': '### Schriftarten: benannt, nie installiert',
        'q': [
            '`qbittorrent` schreibt ein **entpacktes** Qt-UI-Theme nach `%APPDATA%\\qBittorrent\\themes\\wintage` — eine `config.json` (die `Palette.*`-Rollen plus die eigenen Kontextfarben von qBittorrent: Zustände der Transferliste, Log-Schweregrade) und daneben eine `stylesheet.qss` (die 2px-Fasen, die rechten Ecken und Verdana, was eine Palette nicht ausdrücken kann) — und verweist dann `General\\CustomUIThemePath` auf diese `config.json` und setzt `General\\UseCustomUITheme=true`.',
            'Entpackt statt als `.qbtheme`-Paket, und zwar mit Absicht: Eine `.qbtheme` ist eine Qt-Resource-Collection-Datei und bräuchte eine `rcc`-Binärdatei mit passender Hauptversion auf dem Rechner, also eine Compiler-Abhängigkeit für zwei Textdateien. qBittorrent liest die Ordnerform von Haus aus (`FolderThemeSource`).',
            'Schließe qBittorrent vor Apply oder Revert: Es schreibt beim Beenden die ganze `qBittorrent.ini` neu, eine im laufenden Betrieb gemachte Änderung geht beim Schließen also verloren — das Ziel weigert sich in diesem Zustand zu arbeiten, statt einen Erfolg zu melden, den der nächste Programmende-Vorgang löscht. `-Revert` setzt die beiden INI-Schlüssel auf ihre genauen Werte vor Wintage zurück (oder entfernt sie, wenn sie fehlten) und legt einen gleichnamigen Theme-Ordner byteweise wieder hin; unabhängige Änderungen an `qBittorrent.ini` nach Apply bleiben erhalten.',
            'Nicht erreichbar: Symbole in Symbolleiste und Infobereich stammen aus dem eigenen kompilierten Ressourcenpaket von qBittorrent und behalten daher ihre Originalfarben.',
        ],
        'f': [
            'Gesetz 1 in UI.md verlangt Verdana **ohne Kantenglättung**. Ein Qt-Stylesheet kennt dafür keine Eigenschaft, und `OSDFont` von MPC-HC ist nur ein GDI-Schriftname — der einzige Hebel ist die Schrift selbst. `Verdana_m1.ttf` im Repo-Root ist eine Verdana-Kopie mit vorgerenderten 1bpp-Bitmap-Schnitten bei 3–30 ppem, die ein Renderer dem Glätten der Kontur vorzieht.',
            'Die Stylesheets von `qbittorrent` und `obs` nennen `Verdana_m1, Verdana`, und `mpchc` nennt diejenige, die der Rechner tatsächlich auflöst. **Der Installer installiert und deinstalliert keine Schriftart**, und das ist Absicht statt Unfertigkeit:',
            'Eine Schriftfamilie wird über (Familie, Schnitt) aufgelöst. Registriere Regular + Bold + Italic, und jeder Konsument löst korrekt auf; deregistriere **ein** Mitglied, und jeder Konsument, der diese Familie anfragt, zeigt auf ein überlebendes Mitglied. Auf einem Rechner, der `MS Shell Dlg 2` — die Windows-Dialogschrift — über `HKLM\\...\\FontSubstitutes` auf diese Familie aliasiert, macht das Entfernen von Regular den **gesamten Desktop kursiv**, inklusive der Fenstertitel, die der DWM bereits zwischengespeichert hat, und erst ein Abmelden bringt das zurück. Kein Referenzzählen hilft dagegen: Der Streukreis ist maschinenweit, und ein Theme-Installer hat dort nichts zu suchen.',
            'Die Schrift ist deshalb eine einmalige, ausdrückliche Nutzeraktion: Rechtsklick auf `Verdana_m1.ttf` → **Install** (pro Benutzer, kein Administrator nötig), dann das Ziel erneut anwenden. Fehlt die Schrift, sagen die Ziele es einmal, benennen die Lösung und fallen auf Standard-Verdana zurück — kantengeglättet, aber auf dem Rechner passiert nichts hinter deinem Rücken.',
        ],
    },
    'el': {
        'fonts_head': '### Γραμματοσειρές: ονομαστικά, ποτέ εγκατεστημένες',
        'q': [
            'Το `qbittorrent` γράφει ένα **μη συσκευασμένο** θέμα UI Qt στο `%APPDATA%\\qBittorrent\\themes\\wintage` — ένα `config.json` (οι ρόλοι `Palette.*` συν τα δικά του χρώματα συμφραζομένων του qBittorrent: καταστάσεις λίστας μεταφορών, σοβαρότητες καταγραφής) και δίπλα του ένα `stylesheet.qss` (οι λοξοτομές 2px, οι ορθές γωνίες και η Verdana, που μια παλέτα δεν μπορεί να εκφράσει) — και μετά στρέφει το `General\\CustomUIThemePath` σε αυτό το `config.json` και θέτει `General\\UseCustomUITheme=true`.',
            'Μη συσκευασμένο και όχι πακέτο `.qbtheme`, σκόπιμα: ένα `.qbtheme` είναι αρχείο Qt Resource Collection και θα απαιτούσε στο μηχάνημα ένα εκτελέσιμο `rcc` ίδιας κύριας έκδοσης, δηλαδή εξάρτηση από μεταγλωττιστή για δύο αρχεία κειμένου. Το qBittorrent διαβάζει τη μορφή φακέλου εγγενώς (`FolderThemeSource`).',
            'Κλείσε το qBittorrent πριν από Apply ή Revert: ξαναγράφει ολόκληρο το `qBittorrent.ini` στο κλείσιμο, οπότε μια αλλαγή που έγινε ενώ εκτελείται χάνεται στο κλείσιμο — ο στόχος αρνείται να τρέξει σε αυτή την κατάσταση αντί να αναφέρει επιτυχία που το επόμενο κλείσιμο διαγράφει. Το `-Revert` επαναφέρει τα δύο κλειδιά του INI στις ακριβείς τιμές πριν από το Wintage (ή τα αφαιρεί αν έλειπαν) και επιστρέφει τυχόν φάκελο θέματος με το ίδιο όνομα byte προς byte· άσχετες αλλαγές στο `qBittorrent.ini` μετά το Apply επιβιώνουν.',
            'Μη προσβάσιμο: τα εικονίδια της γραμμής εργαλείων και της περιοχής ειδοποιήσεων προέρχονται από το δικό του μεταγλωττισμένο πακέτο πόρων του qBittorrent, οπότε κρατούν τα αρχικά χρώματά τους.',
        ],
        'f': [
            'Ο νόμος 1 του UI.md απαιτεί Verdana **χωρίς εξομάλυνση άκρων**. Ένα stylesheet Qt δεν έχει ιδιότητα γι’ αυτό, και το `OSDFont` του MPC-HC είναι απλώς όνομα γραμματοσειράς GDI — ο μόνος μοχλός είναι η ίδια η γραμματοσειρά. Το `Verdana_m1.ttf` στη ρίζα του αποθετηρίου είναι αντίγραφο της Verdana με προαποδοσμένα bitmap χτυπήματα 1bpp στα 3–30 ppem, που ο renderer τα προτιμά από την εξομάλυνση του περιγράμματος.',
            'Τα stylesheets των `qbittorrent` και `obs` ονομάζουν `Verdana_m1, Verdana`, και το `mpchc` ονομάζει όποια από τις δύο επιλύσει πραγματικά το μηχάνημα. **Ο εγκαταστάτης δεν εγκαθιστά ποτέ ούτε απεγκαθιστά γραμματοσειρά**, και αυτό είναι σκόπιμο και όχι ημιτελές:',
            'Μια οικογένεια γραμματοσειράς επιλύεται κατά (οικογένεια, στυλ). Καταχώρισε Regular + Bold + Italic και κάθε καταναλωτής επιλύει σωστά· απεγγράψε **ένα** μέλος και κάθε καταναλωτής που ζητά αυτή την οικογένεια δείχνει σε ένα μέλος που επιβιώνει. Σε μηχάνημα που δίνει ψευδώνυμο `MS Shell Dlg 2` — τη γραμματοσειρά διαλόγων των Windows — σε αυτή την οικογένεια μέσω `HKLM\\...\\FontSubstitutes`, η αφαίρεση του Regular κάνει **όλη την επιφάνεια εργασίας πλάγια**, μαζί με τίτλους παραθύρων που έχει ήδη προσωρινά αποθηκεύσει ο DWM, και χρειάζεται αποσύνδεση για να επανέλθει. Δεν το διορθώνει κανένα μέτρημα αναφορών: η εμβέλεια είναι σε όλο το μηχάνημα και ένας εγκαταστάτης θεμάτων δεν έχει δουλειά εκεί.',
            'Η γραμματοσειρά είναι λοιπόν μια εφάπαξ, ρητή ενέργεια του χρήστη: δεξί κλικ στο `Verdana_m1.ttf` → **Install** (ανά χρήστη, χωρίς διαχειριστή), και μετά εφάρμοσε ξανά τον στόχο. Αν λείπει η γραμματοσειρά, οι στόχοι το λένε μία φορά, ονομάζουν τη λύση και πέφτουν στην τυπική Verdana — εξομαλυμένη, αλλά τίποτα δεν γίνεται στο μηχάνημα πίσω από την πλάτη σου.',
        ],
    },
    'es': {
        'fonts_head': '### Fuentes: nombradas, nunca instaladas',
        'q': [
            '`qbittorrent` escribe un tema de interfaz Qt **desempaquetado** en `%APPDATA%\\qBittorrent\\themes\\wintage` — un `config.json` (los roles `Palette.*` más los colores de contexto propios de qBittorrent: estados de la lista de transferencias, gravedades del registro) y un `stylesheet.qss` junto a él (los biseles de 2px, las esquinas rectas y Verdana, que una paleta no puede expresar) — y luego apunta `General\\CustomUIThemePath` a ese `config.json` y establece `General\\UseCustomUITheme=true`.',
            'Desempaquetado en lugar de un paquete `.qbtheme`, a propósito: un `.qbtheme` es un archivo Qt Resource Collection y necesitaría un binario `rcc` de versión mayor coincidente en la máquina para producirlo, es decir, una dependencia de compilador para dos archivos de texto. qBittorrent lee la forma de carpeta de forma nativa (`FolderThemeSource`).',
            'Cierra qBittorrent antes de Apply o Revert: reescribe todo `qBittorrent.ini` al salir, así que una edición hecha mientras se ejecuta se descarta al cerrar — el objetivo se niega a ejecutarse en ese estado en lugar de informar de un éxito que el siguiente cierre borra. `-Revert` devuelve las dos claves del INI a sus valores exactos anteriores a Wintage (o las elimina si no estaban) y repone cualquier carpeta de tema con el mismo nombre byte a byte; las ediciones no relacionadas de `qBittorrent.ini` hechas después de Apply sobreviven.',
            'No alcanzable: los iconos de la barra de herramientas y de la bandeja proceden del propio paquete de recursos compilado de qBittorrent, así que conservan sus colores originales.',
        ],
        'f': [
            'La ley 1 de UI.md pide Verdana **sin suavizado**. Un stylesheet de Qt no tiene propiedad para eso, y el `OSDFont` de MPC-HC es solo un nombre de fuente GDI — la única palanca es la propia fuente. `Verdana_m1.ttf` en la raíz del repositorio es una copia de Verdana con trazos de mapa de bits 1bpp pregenerados a 3–30 ppem, que un renderizador prefiere antes que suavizar el contorno.',
            'Los stylesheets de `qbittorrent` y `obs` nombran `Verdana_m1, Verdana`, y `mpchc` nombra la que la máquina resuelva realmente. **El instalador nunca instala ni desinstala una fuente**, y eso es deliberado y no algo a medio hacer:',
            'Una familia tipográfica se resuelve por (familia, estilo). Registra Regular + Bold + Italic y todo consumidor la resuelve bien; da de baja **un** miembro y todo consumidor que pida esa familia apuntará a un miembro superviviente. En una máquina que aliasa `MS Shell Dlg 2` — la fuente de diálogos de Windows — a esa familia mediante `HKLM\\...\\FontSubstitutes`, quitar Regular pone **todo el escritorio en cursiva**, incluidos los títulos de ventana que el DWM ya tiene en caché, y hace falta cerrar sesión para recuperarlo. Ningún recuento de referencias lo arregla: el radio de daño abarca toda la máquina y un instalador de temas no tiene nada que hacer ahí.',
            'Por eso la fuente es una acción puntual y explícita del usuario: clic derecho en `Verdana_m1.ttf` → **Install** (por usuario, sin administrador) y luego vuelve a aplicar el objetivo. Si la fuente falta, los objetivos lo dicen una vez, nombran la solución y recurren a la Verdana normal — suavizada, pero nada se hace en la máquina a tus espaldas.',
        ],
    },
    'fi': {
        'fonts_head': '### Fontit: nimetty, ei koskaan asennettu',
        'q': [
            '`qbittorrent` kirjoittaa **purkamattoman** Qt-käyttöliittymäteeman hakemistoon `%APPDATA%\\qBittorrent\\themes\\wintage` — `config.json` ( `Palette.*`-roolit sekä qBittorrentin omat kontekstivärit: siirtolistan tilat, lokin vakavuustasot) ja sen viereen `stylesheet.qss` (2px:n viisteet, suorat kulmat ja Verdana, joita paletti ei voi ilmaista) — ja osoittaa sitten `General\\CustomUIThemePath`-asetuksen tuohon `config.json`-tiedostoon ja asettaa `General\\UseCustomUITheme=true`.',
            'Purkamattomana eikä `.qbtheme`-pakettina — tarkoituksella: `.qbtheme` on Qt Resource Collection -tiedosto ja sen tuottaminen vaatisi koneelle saman pääversion `rcc`-binäärin, eli kääntäjäriippuvuuden kahden tekstitiedoston takia. qBittorrent lukee kansiomuotoa natiivisti (`FolderThemeSource`).',
            'Sulje qBittorrent ennen Apply- tai Revert-toimintoa: se kirjoittaa koko `qBittorrent.ini`-tiedoston uudelleen lopetettaessa, joten käynnissä ollessa tehty muokkaus häviää sulkiessa — kohde kieltäytyy toimimasta siinä tilassa sen sijaan, että raportoisi onnistumisesta, jonka seuraava lopetus pyyhkii. `-Revert` palauttaa INI:n kaksi avainta täsmälleen Wintagea edeltäneisiin arvoihin (tai poistaa ne, jos niitä ei ollut) ja palauttaa samannimisen teemakansion tavu tavulta; muut Applyn jälkeen tehdyt `qBittorrent.ini`-muokkaukset säilyvät.',
            'Ei tavoitettavissa: työkalupalkin ja ilmaisinalueen kuvakkeet tulevat qBittorrentin omasta käännetytystä resurssipaketista, joten ne säilyttävät alkuperäiset värinsä.',
        ],
        'f': [
            'UI.md:n laki 1 vaatii Verdanan **ilman reunojen pehmennystä**. Qt-tyylitiedostossa ei ole sille ominaisuutta, ja MPC-HC:n `OSDFont` on vain GDI-kirjasinten nimi — ainoa vipu on kirjasin itse. Repon juuressa oleva `Verdana_m1.ttf` on Verdana-kopio, jossa on esirenderöidyt 1bpp-bittikarttaleikkaukset 3–30 ppem -koissa, joita renderöijä käyttää ääriviivan pehmennyksen sijaan.',
            '`qbittorrent`- ja `obs`-tyylitiedostot nimeävät `Verdana_m1, Verdana`, ja `mpchc` nimeää sen kumman kone todella ratkaisee. **Asentaja ei koskaan asenna eikä poista fonttia**, ja se on tarkoituksellista eikä kesken jäänyttä:',
            'Fonttiperhe ratkaistaan parin (perhe, leikkaus) mukaan. Rekisteröi Regular + Bold + Italic, niin jokainen kuluttaja ratkaisee oikein; poista rekisteröinnistä **yksi** jäsen, niin jokainen kyseistä perhettä pyytävä kuluttaja osoittaa jäljelle jääneeseen jäseneen. Koneella, joka aliaksenoi `MS Shell Dlg 2` — Windowsin valintaikkunafontin — tuohon perheeseen `HKLM\\...\\FontSubstitutes`-avaimen kautta, Regularin poistaminen kääntää **koko työpöydän kursiiviksi**, mukaan lukien ikkunan otsikot, jotka DWM on jo välimuistiin tallentanut, ja takaisin saaminen vaatii uloskirjautumisen. Mikään viitelaskenta ei korjaa sitä: vaikutusalue on koneenlaajuinen, eikä teema-asentajalla ole sinne asiaa.',
            'Kirjasin on siis kertaluonteinen, nimenomainen käyttäjän toimi: napsauta `Verdana_m1.ttf` hiiren oikealla → **Install** (käyttäjäkohtaisesti, ei järjestelmänvalvojaa), ja käytä kohde uudelleen. Jos kirjasin puuttuu, kohteet sanovat sen kerran, nimeävät korjauksen ja palaavat tavalliseen Verdanaan — pehmennettynä, mutta koneelle ei tehdä mitään selkäsi takana.',
        ],
    },
    'fr': {
        'fonts_head': '### Polices : nommées, jamais installées',
        'q': [
            '`qbittorrent` écrit un thème d’interface Qt **non empaqueté** dans `%APPDATA%\\qBittorrent\\themes\\wintage` — un `config.json` (les rôles `Palette.*` plus les couleurs contextuelles propres à qBittorrent : états de la liste de transfert, gravités du journal) et un `stylesheet.qss` à côté (les biseaux de 2px, les angles droits et Verdana, qu’une palette ne peut pas exprimer) — puis pointe `General\\CustomUIThemePath` vers ce `config.json` et définit `General\\UseCustomUITheme=true`.',
            'Non empaqueté plutôt qu’un ensemble `.qbtheme`, volontairement : un `.qbtheme` est un fichier Qt Resource Collection et exigerait un binaire `rcc` de même version majeure sur la machine pour être produit, soit une dépendance à un compilateur pour deux fichiers texte. qBittorrent lit nativement la forme en dossier (`FolderThemeSource`).',
            'Fermez qBittorrent avant Apply ou Revert : il réécrit tout `qBittorrent.ini` à la fermeture, donc une modification faite pendant qu’il tourne est perdue à la fermeture — la cible refuse de s’exécuter dans cet état plutôt que d’annoncer une réussite que la prochaine fermeture efface. `-Revert` restaure les deux clés de l’INI à leurs valeurs exactes d’avant Wintage (ou les supprime si elles étaient absentes) et remet en place, octet par octet, tout dossier de thème du même nom ; les modifications sans rapport de `qBittorrent.ini` faites après Apply survivent.',
            'Non accessible : les icônes de la barre d’outils et de la zone de notification viennent du propre paquet de ressources compilé de qBittorrent, elles gardent donc leurs couleurs d’origine.',
        ],
        'f': [
            'La loi 1 d’UI.md demande Verdana **sans anticrénelage**. Une feuille de style Qt n’a pas de propriété pour cela, et `OSDFont` de MPC-HC n’est qu’un nom de fonte GDI — le seul levier est la fonte elle-même. `Verdana_m1.ttf` à la racine du dépôt est une copie de Verdana portant des frappes bitmap 1bpp pré-rendues à 3–30 ppem, qu’un moteur de rendu préfère au lissage du contour.',
            'Les feuilles de style `qbittorrent` et `obs` nomment `Verdana_m1, Verdana`, et `mpchc` nomme celle que la machine résout réellement. **L’installeur n’installe ni ne désinstalle jamais une police**, et c’est délibéré plutôt qu’inachevé :',
            'Une famille de polices se résout par (famille, style). Enregistrez Regular + Bold + Italic et chaque consommateur résout correctement ; désenregistrez **un** membre et chaque consommateur demandant cette famille pointe vers un membre survivant. Sur une machine qui alias `MS Shell Dlg 2` — la police des boîtes de dialogue Windows — vers cette famille via `HKLM\\...\\FontSubstitutes`, retirer Regular met **tout le bureau en italique**, y compris les titres de fenêtres que le DWM a déjà mis en cache, et une déconnexion est nécessaire pour le récupérer. Aucun comptage de références n’y remédie : le rayon d’impact couvre toute la machine et un installeur de thèmes n’a rien à y faire.',
            'La fonte est donc une action ponctuelle et explicite de l’utilisateur : clic droit sur `Verdana_m1.ttf` → **Install** (par utilisateur, sans administrateur), puis réappliquez la cible. Si la fonte est absente, les cibles le disent une fois, nomment la solution et se rabattent sur la Verdana standard — anticrénelée, mais rien n’est fait à la machine dans votre dos.',
        ],
    },
    'he': {
        'fonts_head': '### גופנים: נקובים בשם, ולעולם לא מותקנים',
        'q': [
            '`qbittorrent` כותב ערכת ממשק Qt **לא ארוזה** אל `%APPDATA%\\qBittorrent\\themes\\wintage` — קובץ `config.json` (תפקידי `Palette.*` בתוספת צבעי ההקשר של qBittorrent עצמו: מצבי רשימת ההעברות, חומרת היומן) ולצדו `stylesheet.qss` (שיפועי ה-2px, הפינות הישרות ו-Verdana, שאלה שהפלטה אינה יכולה לבטא) — ואז מפנה את `General\\CustomUIThemePath` אל אותו `config.json` ומגדיר `General\\UseCustomUITheme=true`.',
            'לא ארוזה ולא כחבילת `.qbtheme`, בכוונה: קובץ `.qbtheme` הוא קובץ Qt Resource Collection והפקתו הייתה דורשת במכונה קובץ הרצה `rcc` עם אותה גרסה ראשית, כלומר תלות במהדר עבור שני קובצי טקסט. qBittorrent קורא את צורת התיקייה באופן מקורי (`FolderThemeSource`).',
            'סגרו את qBittorrent לפני Apply או Revert: הוא כותב מחדש את כל `qBittorrent.ini` ביציאה, ולכן עריכה שנעשתה בזמן שהוא רץ נמחקת בסגירה — היעד מסרב לפעול במצב הזה במקום לדווח על הצלחה שהיציאה הבאה מוחקת. `-Revert` מחזיר את שני מפתחות ה-INI לערכם המדויק מלפני Wintage (או מסיר אותם אם לא היו) ומשיב כל תיקיית ערכה בשם זהה בית-בית; עריכות אחרות ב-`qBittorrent.ini` שנעשו אחרי Apply נשמרות.',
            'לא ניתן להגיע: סמלי סרגל הכלים ומגש המערכת מגיעים מחבילת המשאבים המקומפלת של qBittorrent עצמו, ולכן הם שומרים על צבעיהם המקוריים.',
        ],
        'f': [
            'החוק הראשון ב-UI.md דורש Verdana **בלי החלקת קצוות**. לגיליון סגנונות של Qt אין מאפיין לכך, ו-`OSDFont` של MPC-HC הוא רק שם גופן GDI — המנוף היחיד הוא הגופן עצמו. הקובץ `Verdana_m1.ttf` בשורש המאגר הוא עותק של Verdana הנושא רישומי מפת סיביות 1bpp מרונדרים מראש בגודל 3–30 ppem, שמנוע הרינדור מעדיף על החלקת קווי המתאר.',
            'גיליונות הסגנונות של `qbittorrent` ו-`obs` מציינים `Verdana_m1, Verdana`, ו-`mpchc` מציין את זה מהשניים שהמכונה באמת מפענחת. **המתקין לעולם אינו מתקין ואינו מסיר גופן**, וזו החלטה מכוונת ולא עבודה שלא הושלמה:',
            'משפחת גופנים נפתרת לפי (משפחה, סגנון). רשמו Regular + Bold + Italic וכל צרכן יפתור נכון; בטלו רישום של **חבר אחד** וכל צרכן שמבקש את המשפחה הזו יצביע על חבר שנותר. במכונה שממפה את `MS Shell Dlg 2` — גופן תיבות הדו-שיח של Windows — למשפחה הזו דרך `HKLM\\...\\FontSubstitutes`, הסרת Regular הופכת את **כל שולחן העבודה לנטוי**, כולל כותרות חלונות ש-DWM כבר שמר במטמון, ונדרשת התנתקות כדי להחזיר זאת. שום ספירת מפנים לא מתקנת זאת: רדיוס הפגיעה חובק את כל המכונה, ולמתקין ערכות אין שם עסק.',
            'לכן הגופן הוא פעולה חד-פעמית ומפורשת של המשתמש: לחיצה ימנית על `Verdana_m1.ttf` ← **Install** (למשתמש הנוכחי, בלי מנהל), ואז הפעילו את היעד מחדש. אם הגופן חסר, היעדים אומרים זאת פעם אחת, נוקבים בפתרון וחוזרים ל-Verdana הרגיל — מוחלק, אבל שום דבר לא נעשה במכונה מאחורי גבכם.',
        ],
    },
}
