#!/usr/bin/env node
// Writes the palettes in themes/*.json into a wintage.user.js.
//
// Why this exists: the userscript is one file that Tampermonkey re-downloads on
// every update, so a palette edited into it by hand is gone the next time upstream
// ships. Keeping the palettes as separate JSON and re-applying them turns "my
// themes" from something you lose on upgrade into something you re-install in one
// command — which is the whole point of the packs.
//
// Two modes of finding the block to replace, in this order:
//   1. Between the generated markers, if the target already has them.
//   2. Otherwise, the `const THEMES = { … };` declaration itself, located by brace
//      depth — and the markers get added around the replacement, so a plain
//      upstream file is upgraded to a marked one on first run.
// Mode 2 is what makes this work against a version of the script this tool has
// never seen, which is the case that actually matters after an upgrade.
//
// Usage:
//   node tools/apply-themes.js                  # apply into ../wintage.user.js
//   node tools/apply-themes.js <path>           # apply into some other copy
//   node tools/apply-themes.js --check          # exit 1 if the file is out of date
//
// Idempotent: applying twice produces a byte-identical file.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const THEME_DIR = path.join(ROOT, 'themes');

const BEGIN = '  // ─── THEME PACKS ── GENERATED by tools/apply-themes.js, DO NOT EDIT BY HAND ──';
const END = '  // ─── END THEME PACKS ─────────────────────────────────────────────────────────';

const REQUIRED_TOKENS = [
  'background', 'backgroundSoft',
  'surface', 'surfaceRaised', 'surfaceAlt',
  'borderDark', 'borderHighlight', 'borderMuted',
  'textPrimary', 'textSecondary', 'textMuted',
  'accentTeal', 'accentTealDeep',
  'success', 'warning', 'danger',
  'selection', 'compareBack', 'link'
];

function die(msg) { console.error('apply-themes: ' + msg); process.exit(1); }

function loadThemes() {
  if (!fs.existsSync(THEME_DIR)) die('no themes/ directory at ' + THEME_DIR);
  const files = fs.readdirSync(THEME_DIR).filter(f => f.endsWith('.json')).sort();
  if (!files.length) die('themes/ holds no .json packs');
  const themes = [];
  for (const f of files) {
    let pack;
    try { pack = JSON.parse(fs.readFileSync(path.join(THEME_DIR, f), 'utf8').replace(/^\uFEFF/, '')); }
    catch (e) { die(f + ': not valid JSON — ' + e.message); }
    const slug = pack.slug || path.basename(f, '.json');
    if (!/^[a-z][a-z0-9]*$/.test(slug)) die(f + ': slug "' + slug + '" must be lowercase alphanumeric (it becomes a JS identifier)');
    if (!pack.label) die(f + ': no label');
    if (pack.label.includes("'")) die(f + ": label must not contain an apostrophe (it is emitted inside single quotes)");
    for (const t of REQUIRED_TOKENS) {
      const v = pack.tokens && pack.tokens[t];
      if (!v) die(f + ': missing token ' + t);
      if (!/^#[0-9A-Fa-f]{6}$/.test(v)) die(f + ': token ' + t + ' = "' + v + '" is not a 6-digit hex');
    }
    const extra = Object.keys(pack.tokens).filter(k => !REQUIRED_TOKENS.includes(k));
    if (extra.length) die(f + ': unknown token(s) ' + extra.join(', '));
    themes.push({ slug, label: pack.label, order: typeof pack.order === 'number' ? pack.order : 99, tokens: pack.tokens });
  }
  // Menu order is the pack's own `order`, ties broken by slug — so the list a user
  // sees does not silently reshuffle when a pack is added.
  themes.sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
  return themes;
}

function render(themes) {
  const out = [BEGIN, '  const THEMES = {'];
  themes.forEach((t, i) => {
    out.push('    ' + t.slug + ': {');
    out.push("      label: '" + t.label + "',");
    out.push('      tokens: {');
    const lines = [
      ['background', 'backgroundSoft'],
      ['surface', 'surfaceRaised', 'surfaceAlt'],
      ['borderDark', 'borderHighlight', 'borderMuted'],
      ['textPrimary', 'textSecondary', 'textMuted'],
      ['accentTeal', 'accentTealDeep'],
      ['success', 'warning', 'danger'],
      ['selection', 'compareBack'],
      ['link']
    ];
    lines.forEach((group, gi) => {
      const body = group.map(k => k + ": '" + t.tokens[k].toUpperCase() + "'").join(', ');
      out.push('        ' + body + (gi === lines.length - 1 ? '' : ','));
    });
    out.push('      }');
    out.push('    }' + (i === themes.length - 1 ? '' : ','));
  });
  out.push('  };');
  out.push(END);
  return out.join('\n');
}

// Locate the block to replace. Returns [start, end) offsets into src.
function locate(src) {
  const b = src.indexOf(BEGIN);
  if (b >= 0) {
    const e = src.indexOf(END, b);
    if (e < 0) die('found the opening marker but not the closing one — refusing to guess where the block ends');
    return [b, e + END.length];
  }
  const d = src.indexOf('const THEMES = {');
  if (d < 0) die('target has neither the generated markers nor a `const THEMES = {` declaration — is this a Wintage script?');
  // Walk to the declaration's own closing brace, then past the `;`.
  let depth = 0, k = src.indexOf('{', d), end = -1;
  for (; k < src.length; k++) {
    if (src[k] === '{') depth++;
    else if (src[k] === '}') { depth--; if (depth === 0) { end = k; break; } }
  }
  if (end < 0) die('`const THEMES` has no closing brace');
  while (end < src.length && src[end] !== ';') end++;
  // Include the whole line the declaration starts on, so indentation stays clean.
  const lineStart = src.lastIndexOf('\n', d) + 1;
  return [lineStart, end + 1];
}

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const target = path.resolve(args.find(a => !a.startsWith('--')) || path.join(ROOT, 'wintage.user.js'));
if (!fs.existsSync(target)) die('target not found: ' + target);

const themes = loadThemes();
const src = fs.readFileSync(target, 'utf8');
const [start, end] = locate(src);
const next = src.slice(0, start) + render(themes) + src.slice(end);

if (next === src) {
  console.log('apply-themes: ' + path.basename(target) + ' already up to date (' + themes.length + ' theme(s): ' + themes.map(t => t.slug).join(', ') + ')');
  process.exit(0);
}
if (checkOnly) {
  console.error('apply-themes: ' + path.basename(target) + ' is OUT OF DATE — run `node tools/apply-themes.js`');
  process.exit(1);
}
fs.writeFileSync(target, next);
console.log('apply-themes: wrote ' + themes.length + ' theme(s) into ' + path.basename(target) + ' — ' + themes.map(t => t.slug).join(', '));
